<?php

$countriesData = array(
	["name"=>"Afghanistan","language"=>"Pashto","two_letter_code"=>"ps-AF","three_letter_code"=>"ps-AFG","locale_id"=>"1123"],
	["name"=>"Afghanistan","language"=>"Persian","two_letter_code"=>"fa-AF","three_letter_code"=>"fa-AFG","locale_id"=>"4096"],
	["name"=>"Afghanistan","language"=>"Uzbek","two_letter_code"=>"uz-AF","three_letter_code"=>"uz-AFG","locale_id"=>"4096"],
	["name"=>"Åland Islands","language"=>"Swedish","two_letter_code"=>"sv-AX","three_letter_code"=>"sv-ALA","locale_id"=>"4096"],
	["name"=>"Albania","language"=>"Albanian","two_letter_code"=>"sq-AL","three_letter_code"=>"sq-ALB","locale_id"=>"1052"],
	["name"=>"Albania","language"=>"English","two_letter_code"=>"en-AL","three_letter_code"=>"en-ALB","locale_id"=>"4096"],
	["name"=>"Algeria","language"=>"Arabic","two_letter_code"=>"ar-DZ","three_letter_code"=>"ar-DZA","locale_id"=>"5121"],
	["name"=>"Algeria","language"=>"French","two_letter_code"=>"fr-DZ","three_letter_code"=>"fr-DZA","locale_id"=>"4096"],
	["name"=>"Algeria","language"=>"Kabyle","two_letter_code"=>"kab-DZ","three_letter_code"=>"kab-DZA","locale_id"=>"4096"],
	["name"=>"American Samoa","language"=>"English","two_letter_code"=>"en-AS","three_letter_code"=>"en-ASM","locale_id"=>"4096"],
	["name"=>"Andorra","language"=>"Catalan","two_letter_code"=>"ca-AD","three_letter_code"=>"ca-AND","locale_id"=>"4096"],
	["name"=>"Andorra","language"=>"English","two_letter_code"=>"en-AD","three_letter_code"=>"en-AND","locale_id"=>"4096"],
	["name"=>"Angola","language"=>"Lingala","two_letter_code"=>"ln-AO","three_letter_code"=>"ln-AGO","locale_id"=>"4096"],
	["name"=>"Angola","language"=>"Portuguese","two_letter_code"=>"pt-AO","three_letter_code"=>"pt-AGO","locale_id"=>"4096"],
	["name"=>"Anguilla","language"=>"English","two_letter_code"=>"en-AI","three_letter_code"=>"en-AIA","locale_id"=>"4096"],
	["name"=>"Anguilla","language"=>"Spanish","two_letter_code"=>"es-AI","three_letter_code"=>"es-AIA","locale_id"=>"4096"],
	["name"=>"Antigua &amp; Barbuda","language"=>"English","two_letter_code"=>"en-AG","three_letter_code"=>"en-ATG","locale_id"=>"4096"],
	["name"=>"Antigua &amp; Barbuda","language"=>"Spanish","two_letter_code"=>"es-AG","three_letter_code"=>"es-ATG","locale_id"=>"4096"],
	["name"=>"Argentina","language"=>"English","two_letter_code"=>"en-AR","three_letter_code"=>"en-ARG","locale_id"=>"4096"],
	["name"=>"Argentina","language"=>"Spanish","two_letter_code"=>"es-AR","three_letter_code"=>"es-ARG","locale_id"=>"11274"],
	["name"=>"Armenia","language"=>"Armenian","two_letter_code"=>"hy-AM","three_letter_code"=>"hy-ARM","locale_id"=>"1067"],
	["name"=>"Aruba","language"=>"Dutch","two_letter_code"=>"nl-AW","three_letter_code"=>"nl-ABW","locale_id"=>"4096"],
	["name"=>"Aruba","language"=>"Spanish","two_letter_code"=>"es-AW","three_letter_code"=>"es-ABW","locale_id"=>"4096"],
	["name"=>"Australia","language"=>"English","two_letter_code"=>"en-AU","three_letter_code"=>"en-AUS","locale_id"=>"3081"],
	["name"=>"Austria","language"=>"English","two_letter_code"=>"en-AT","three_letter_code"=>"en-AUT","locale_id"=>"4096"],
	["name"=>"Austria","language"=>"German","two_letter_code"=>"de-AT","three_letter_code"=>"de-AUT","locale_id"=>"3079"],
	["name"=>"Azerbaijan","language"=>"Azerbaijani","two_letter_code"=>"az-AZ","three_letter_code"=>"az-AZE","locale_id"=>"1068"],
	["name"=>"Azerbaijan","language"=>"Azerbaijani","two_letter_code"=>"az-AZ","three_letter_code"=>"az-AZE","locale_id"=>"2092"],
	["name"=>"Bahamas","language"=>"English","two_letter_code"=>"en-BS","three_letter_code"=>"en-BHS","locale_id"=>"4096"],
	["name"=>"Bahamas","language"=>"Spanish","two_letter_code"=>"es-BS","three_letter_code"=>"es-BHS","locale_id"=>"4096"],
	["name"=>"Bahrain","language"=>"Arabic","two_letter_code"=>"ar-BH","three_letter_code"=>"ar-BHR","locale_id"=>"15361"],
	["name"=>"Bangladesh","language"=>"Bangla","two_letter_code"=>"bn-BD","three_letter_code"=>"bn-BGD","locale_id"=>"2117"],
	["name"=>"Bangladesh","language"=>"Chakma","two_letter_code"=>"ccp-BD","three_letter_code"=>"ccp-BGD","locale_id"=>"4096"],
	["name"=>"Bangladesh","language"=>"English","two_letter_code"=>"en-BD","three_letter_code"=>"en-BGD","locale_id"=>"4096"],
	["name"=>"Barbados","language"=>"English","two_letter_code"=>"en-BB","three_letter_code"=>"en-BRB","locale_id"=>"4096"],
	["name"=>"Barbados","language"=>"Spanish","two_letter_code"=>"es-BB","three_letter_code"=>"es-BRB","locale_id"=>"4096"],
	["name"=>"Belarus","language"=>"Belarusian","two_letter_code"=>"be-BY","three_letter_code"=>"be-BLR","locale_id"=>"1059"],
	["name"=>"Belarus","language"=>"Russian","two_letter_code"=>"ru-BY","three_letter_code"=>"ru-BLR","locale_id"=>"4096"],
	["name"=>"Belgium","language"=>"Dutch","two_letter_code"=>"nl-BE","three_letter_code"=>"nl-BEL","locale_id"=>"2067"],
	["name"=>"Belgium","language"=>"English","two_letter_code"=>"en-BE","three_letter_code"=>"en-BEL","locale_id"=>"4096"],
	["name"=>"Belgium","language"=>"French","two_letter_code"=>"fr-BE","three_letter_code"=>"fr-BEL","locale_id"=>"2060"],
	["name"=>"Belgium","language"=>"German","two_letter_code"=>"de-BE","three_letter_code"=>"de-BEL","locale_id"=>"4096"],
	["name"=>"Belgium","language"=>"Walloon","two_letter_code"=>"wa-BE","three_letter_code"=>"wa-BEL","locale_id"=>"4096"],
	["name"=>"Belize","language"=>"English","two_letter_code"=>"en-BZ","three_letter_code"=>"en-BLZ","locale_id"=>"10249"],
	["name"=>"Belize","language"=>"Spanish","two_letter_code"=>"es-BZ","three_letter_code"=>"es-BLZ","locale_id"=>"4096"],
	["name"=>"Benin","language"=>"French","two_letter_code"=>"fr-BJ","three_letter_code"=>"fr-BEN","locale_id"=>"4096"],
	["name"=>"Benin","language"=>"Yoruba","two_letter_code"=>"yo-BJ","three_letter_code"=>"yo-BEN","locale_id"=>"4096"],
	["name"=>"Bermuda","language"=>"English","two_letter_code"=>"en-BM","three_letter_code"=>"en-BMU","locale_id"=>"4096"],
	["name"=>"Bermuda","language"=>"Spanish","two_letter_code"=>"es-BM","three_letter_code"=>"es-BMU","locale_id"=>"4096"],
	["name"=>"Bhutan","language"=>"Dzongkha","two_letter_code"=>"dz-BT","three_letter_code"=>"dz-BTN","locale_id"=>"3153"],
	["name"=>"Bolivia","language"=>"Quechua","two_letter_code"=>"qu-BO","three_letter_code"=>"qu-BOL","locale_id"=>"4096"],
	["name"=>"Bolivia","language"=>"Spanish","two_letter_code"=>"es-BO","three_letter_code"=>"es-BOL","locale_id"=>"16394"],
	["name"=>"Bosnia &amp; Herzegovina","language"=>"Bosnian","two_letter_code"=>"bs-BA","three_letter_code"=>"bs-BIH","locale_id"=>"5146"],
	["name"=>"Bosnia &amp; Herzegovina","language"=>"Bosnian","two_letter_code"=>"bs-BA","three_letter_code"=>"bs-BIH","locale_id"=>"8218"],
	["name"=>"Bosnia &amp; Herzegovina","language"=>"Croatian","two_letter_code"=>"hr-BA","three_letter_code"=>"hr-BIH","locale_id"=>"4122"],
	["name"=>"Bosnia &amp; Herzegovina","language"=>"English","two_letter_code"=>"en-BA","three_letter_code"=>"en-BIH","locale_id"=>"4096"],
	["name"=>"Bosnia &amp; Herzegovina","language"=>"Serbian","two_letter_code"=>"sr-BA","three_letter_code"=>"sr-BIH","locale_id"=>"6170"],
	["name"=>"Bosnia &amp; Herzegovina","language"=>"Serbian","two_letter_code"=>"sr-BA","three_letter_code"=>"sr-BIH","locale_id"=>"7194"],
	["name"=>"Botswana","language"=>"English","two_letter_code"=>"en-BW","three_letter_code"=>"en-BWA","locale_id"=>"4096"],
	["name"=>"Botswana","language"=>"Tswana","two_letter_code"=>"tn-BW","three_letter_code"=>"tn-BWA","locale_id"=>"2098"],
	["name"=>"Brazil","language"=>"English","two_letter_code"=>"en-BR","three_letter_code"=>"en-BRA","locale_id"=>"4096"],
	["name"=>"Brazil","language"=>"Portuguese","two_letter_code"=>"pt-BR","three_letter_code"=>"pt-BRA","locale_id"=>"1046"],
	["name"=>"Brazil","language"=>"Spanish","two_letter_code"=>"es-BR","three_letter_code"=>"es-BRA","locale_id"=>"4096"],
	["name"=>"British Indian Ocean Territory","language"=>"English","two_letter_code"=>"en-IO","three_letter_code"=>"en-IOT","locale_id"=>"4096"],
	["name"=>"British Virgin Islands","language"=>"English","two_letter_code"=>"en-VG","three_letter_code"=>"en-VGB","locale_id"=>"4096"],
	["name"=>"British Virgin Islands","language"=>"Spanish","two_letter_code"=>"es-VG","three_letter_code"=>"es-VGB","locale_id"=>"4096"],
	["name"=>"Brunei","language"=>"Malay","two_letter_code"=>"ms-BN","three_letter_code"=>"ms-BRN","locale_id"=>"2110"],
	["name"=>"Brunei","language"=>"Malay","two_letter_code"=>"ms-BN","three_letter_code"=>"ms-BRN","locale_id"=>"4096"],
	["name"=>"Bulgaria","language"=>"Bulgarian","two_letter_code"=>"bg-BG","three_letter_code"=>"bg-BGR","locale_id"=>"1026"],
	["name"=>"Bulgaria","language"=>"English","two_letter_code"=>"en-BG","three_letter_code"=>"en-BGR","locale_id"=>"4096"],
	["name"=>"Burkina Faso","language"=>"French","two_letter_code"=>"fr-BF","three_letter_code"=>"fr-BFA","locale_id"=>"4096"],
	["name"=>"Burkina Faso","language"=>"Fulah","two_letter_code"=>"ff-BF","three_letter_code"=>"ff-BFA","locale_id"=>"4096"],
	["name"=>"Burundi","language"=>"English","two_letter_code"=>"en-BI","three_letter_code"=>"en-BDI","locale_id"=>"4096"],
	["name"=>"Burundi","language"=>"French","two_letter_code"=>"fr-BI","three_letter_code"=>"fr-BDI","locale_id"=>"4096"],
	["name"=>"Burundi","language"=>"Rundi","two_letter_code"=>"rn-BI","three_letter_code"=>"rn-BDI","locale_id"=>"4096"],
	["name"=>"Cambodia","language"=>"Khmer","two_letter_code"=>"km-KH","three_letter_code"=>"km-KHM","locale_id"=>"1107"],
	["name"=>"Cameroon","language"=>"Aghem","two_letter_code"=>"agq-CM","three_letter_code"=>"agq-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Bafia","two_letter_code"=>"ksf-CM","three_letter_code"=>"ksf-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Basaa","two_letter_code"=>"bas-CM","three_letter_code"=>"bas-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Duala","two_letter_code"=>"dua-CM","three_letter_code"=>"dua-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"English","two_letter_code"=>"en-CM","three_letter_code"=>"en-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Ewondo","two_letter_code"=>"ewo-CM","three_letter_code"=>"ewo-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"French","two_letter_code"=>"fr-CM","three_letter_code"=>"fr-CMR","locale_id"=>"11276"],
	["name"=>"Cameroon","language"=>"Fulah","two_letter_code"=>"ff-CM","three_letter_code"=>"ff-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Kako","two_letter_code"=>"kkj-CM","three_letter_code"=>"kkj-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Kwasio","two_letter_code"=>"nmg-CM","three_letter_code"=>"nmg-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Metaʼ","two_letter_code"=>"mgo-CM","three_letter_code"=>"mgo-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Mundang","two_letter_code"=>"mua-CM","three_letter_code"=>"mua-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Ngiemboon","two_letter_code"=>"nnh-CM","three_letter_code"=>"nnh-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Ngomba","two_letter_code"=>"jgo-CM","three_letter_code"=>"jgo-CMR","locale_id"=>"4096"],
	["name"=>"Cameroon","language"=>"Yangben","two_letter_code"=>"yav-CM","three_letter_code"=>"yav-CMR","locale_id"=>"4096"],
	["name"=>"Canada","language"=>"English","two_letter_code"=>"en-CA","three_letter_code"=>"en-CAN","locale_id"=>"4105"],
	["name"=>"Canada","language"=>"French","two_letter_code"=>"fr-CA","three_letter_code"=>"fr-CAN","locale_id"=>"3084"],
	["name"=>"Canada","language"=>"Inuktitut","two_letter_code"=>"iu-CA","three_letter_code"=>"iu-CAN","locale_id"=>"4096"],
	["name"=>"Canada","language"=>"Mohawk","two_letter_code"=>"moh-CA","three_letter_code"=>"moh-CAN","locale_id"=>"1148"],
	["name"=>"Canada","language"=>"Spanish","two_letter_code"=>"es-CA","three_letter_code"=>"es-CAN","locale_id"=>"4096"],
	["name"=>"Canary Islands","language"=>"Spanish","two_letter_code"=>"es-IC","three_letter_code"=>"es-IC ","locale_id"=>"4096"],
	["name"=>"Cape Verde","language"=>"Kabuverdianu","two_letter_code"=>"kea-CV","three_letter_code"=>"kea-CPV","locale_id"=>"4096"],
	["name"=>"Cape Verde","language"=>"Portuguese","two_letter_code"=>"pt-CV","three_letter_code"=>"pt-CPV","locale_id"=>"4096"],
	["name"=>"Caribbean Netherlands","language"=>"Dutch","two_letter_code"=>"nl-BQ","three_letter_code"=>"nl-BES","locale_id"=>"4096"],
	["name"=>"Caribbean Netherlands","language"=>"Spanish","two_letter_code"=>"es-BQ","three_letter_code"=>"es-BES","locale_id"=>"4096"],
	["name"=>"Cayman Islands","language"=>"English","two_letter_code"=>"en-KY","three_letter_code"=>"en-CYM","locale_id"=>"4096"],
	["name"=>"Cayman Islands","language"=>"Spanish","two_letter_code"=>"es-KY","three_letter_code"=>"es-CYM","locale_id"=>"4096"],
	["name"=>"Central African Republic","language"=>"French","two_letter_code"=>"fr-CF","three_letter_code"=>"fr-CAF","locale_id"=>"4096"],
	["name"=>"Central African Republic","language"=>"Lingala","two_letter_code"=>"ln-CF","three_letter_code"=>"ln-CAF","locale_id"=>"4096"],
	["name"=>"Central African Republic","language"=>"Sango","two_letter_code"=>"sg-CF","three_letter_code"=>"sg-CAF","locale_id"=>"4096"],
	["name"=>"Ceuta &amp; Melilla","language"=>"Spanish","two_letter_code"=>"es-EA","three_letter_code"=>"es-EA ","locale_id"=>"4096"],
	["name"=>"Chad","language"=>"Arabic","two_letter_code"=>"ar-TD","three_letter_code"=>"ar-TCD","locale_id"=>"4096"],
	["name"=>"Chad","language"=>"French","two_letter_code"=>"fr-TD","three_letter_code"=>"fr-TCD","locale_id"=>"4096"],
	["name"=>"Chile","language"=>"English","two_letter_code"=>"en-CL","three_letter_code"=>"en-CHL","locale_id"=>"4096"],
	["name"=>"Chile","language"=>"Mapuche","two_letter_code"=>"arn-CL","three_letter_code"=>"arn-CHL","locale_id"=>"1146"],
	["name"=>"Chile","language"=>"Spanish","two_letter_code"=>"es-CL","three_letter_code"=>"es-CHL","locale_id"=>"13322"],
	["name"=>"China mainland","language"=>"Cantonese","two_letter_code"=>"yue-CN","three_letter_code"=>"yue-CHN","locale_id"=>"4096"],
	["name"=>"China mainland","language"=>"Chinese","two_letter_code"=>"zh-CN","three_letter_code"=>"zh-CHN","locale_id"=>"4096"],
	["name"=>"China mainland","language"=>"Chinese","two_letter_code"=>"zh-CN","three_letter_code"=>"zh-CHN","locale_id"=>"4096"],
	["name"=>"China mainland","language"=>"English","two_letter_code"=>"en-CN","three_letter_code"=>"en-CHN","locale_id"=>"4096"],
	["name"=>"China mainland","language"=>"Sichuan Yi","two_letter_code"=>"ii-CN","three_letter_code"=>"ii-CHN","locale_id"=>"1144"],
	["name"=>"China mainland","language"=>"Tibetan","two_letter_code"=>"bo-CN","three_letter_code"=>"bo-CHN","locale_id"=>"1105"],
	["name"=>"China mainland","language"=>"Uyghur","two_letter_code"=>"ug-CN","three_letter_code"=>"ug-CHN","locale_id"=>"1152"],
	["name"=>"Christmas Island","language"=>"English","two_letter_code"=>"en-CX","three_letter_code"=>"en-CXR","locale_id"=>"4096"],
	["name"=>"Cocos (Keeling], Islands","language"=>"English","two_letter_code"=>"en-CC","three_letter_code"=>"en-CCK","locale_id"=>"4096"],
	["name"=>"Colombia","language"=>"English","two_letter_code"=>"en-CO","three_letter_code"=>"en-COL","locale_id"=>"4096"],
	["name"=>"Colombia","language"=>"Spanish","two_letter_code"=>"es-CO","three_letter_code"=>"es-COL","locale_id"=>"9226"],
	["name"=>"Comoros","language"=>"Arabic","two_letter_code"=>"ar-KM","three_letter_code"=>"ar-COM","locale_id"=>"4096"],
	["name"=>"Comoros","language"=>"French","two_letter_code"=>"fr-KM","three_letter_code"=>"fr-COM","locale_id"=>"4096"],
	["name"=>"Congo - Brazzaville","language"=>"French","two_letter_code"=>"fr-CG","three_letter_code"=>"fr-COG","locale_id"=>"4096"],
	["name"=>"Congo - Brazzaville","language"=>"Lingala","two_letter_code"=>"ln-CG","three_letter_code"=>"ln-COG","locale_id"=>"4096"],
	["name"=>"Congo - Kinshasa","language"=>"French","two_letter_code"=>"fr-CD","three_letter_code"=>"fr-COD","locale_id"=>"9228"],
	["name"=>"Congo - Kinshasa","language"=>"Lingala","two_letter_code"=>"ln-CD","three_letter_code"=>"ln-COD","locale_id"=>"4096"],
	["name"=>"Congo - Kinshasa","language"=>"Luba-Katanga","two_letter_code"=>"lu-CD","three_letter_code"=>"lu-COD","locale_id"=>"4096"],
	["name"=>"Congo - Kinshasa","language"=>"Swahili","two_letter_code"=>"sw-CD","three_letter_code"=>"sw-COD","locale_id"=>"4096"],
	["name"=>"Cook Islands","language"=>"English","two_letter_code"=>"en-CK","three_letter_code"=>"en-COK","locale_id"=>"4096"],
	["name"=>"Costa Rica","language"=>"Spanish","two_letter_code"=>"es-CR","three_letter_code"=>"es-CRI","locale_id"=>"5130"],
	["name"=>"Côte d’Ivoire","language"=>"French","two_letter_code"=>"fr-CI","three_letter_code"=>"fr-CIV","locale_id"=>"12300"],
	["name"=>"Croatia","language"=>"Croatian","two_letter_code"=>"hr-HR","three_letter_code"=>"hr-HRV","locale_id"=>"1050"],
	["name"=>"Croatia","language"=>"English","two_letter_code"=>"en-HR","three_letter_code"=>"en-HRV","locale_id"=>"4096"],
	["name"=>"Cuba","language"=>"Spanish","two_letter_code"=>"es-CU","three_letter_code"=>"es-CUB","locale_id"=>"23562"],
	["name"=>"Curaçao","language"=>"Dutch","two_letter_code"=>"nl-CW","three_letter_code"=>"nl-CUW","locale_id"=>"4096"],
	["name"=>"Curaçao","language"=>"Spanish","two_letter_code"=>"es-CW","three_letter_code"=>"es-CUW","locale_id"=>"4096"],
	["name"=>"Cyprus","language"=>"English","two_letter_code"=>"en-CY","three_letter_code"=>"en-CYP","locale_id"=>"4096"],
	["name"=>"Cyprus","language"=>"Greek","two_letter_code"=>"el-CY","three_letter_code"=>"el-CYP","locale_id"=>"4096"],
	["name"=>"Cyprus","language"=>"Turkish","two_letter_code"=>"tr-CY","three_letter_code"=>"tr-CYP","locale_id"=>"4096"],
	["name"=>"Czechia","language"=>"Czech","two_letter_code"=>"cs-CZ","three_letter_code"=>"cs-CZE","locale_id"=>"1029"],
	["name"=>"Czechia","language"=>"English","two_letter_code"=>"en-CZ","three_letter_code"=>"en-CZE","locale_id"=>"4096"],
	["name"=>"Denmark","language"=>"Danish","two_letter_code"=>"da-DK","three_letter_code"=>"da-DNK","locale_id"=>"1030"],
	["name"=>"Denmark","language"=>"English","two_letter_code"=>"en-DK","three_letter_code"=>"en-DNK","locale_id"=>"4096"],
	["name"=>"Denmark","language"=>"Faroese","two_letter_code"=>"fo-DK","three_letter_code"=>"fo-DNK","locale_id"=>"4096"],
	["name"=>"Diego Garcia","language"=>"English","two_letter_code"=>"en-DG","three_letter_code"=>"en-DGA","locale_id"=>"4096"],
	["name"=>"Djibouti","language"=>"Arabic","two_letter_code"=>"ar-DJ","three_letter_code"=>"ar-DJI","locale_id"=>"4096"],
	["name"=>"Djibouti","language"=>"French","two_letter_code"=>"fr-DJ","three_letter_code"=>"fr-DJI","locale_id"=>"4096"],
	["name"=>"Djibouti","language"=>"Somali","two_letter_code"=>"so-DJ","three_letter_code"=>"so-DJI","locale_id"=>"4096"],
	["name"=>"Dominica","language"=>"English","two_letter_code"=>"en-DM","three_letter_code"=>"en-DMA","locale_id"=>"4096"],
	["name"=>"Dominica","language"=>"Spanish","two_letter_code"=>"es-DM","three_letter_code"=>"es-DMA","locale_id"=>"4096"],
	["name"=>"Dominican Republic","language"=>"Spanish","two_letter_code"=>"es-DO","three_letter_code"=>"es-DOM","locale_id"=>"7178"],
	["name"=>"Ecuador","language"=>"Quechua","two_letter_code"=>"qu-EC","three_letter_code"=>"qu-ECU","locale_id"=>"4096"],
	["name"=>"Ecuador","language"=>"Spanish","two_letter_code"=>"es-EC","three_letter_code"=>"es-ECU","locale_id"=>"12298"],
	["name"=>"Egypt","language"=>"Arabic","two_letter_code"=>"ar-EG","three_letter_code"=>"ar-EGY","locale_id"=>"3073"],
	["name"=>"El Salvador","language"=>"Spanish","two_letter_code"=>"es-SV","three_letter_code"=>"es-SLV","locale_id"=>"17418"],
	["name"=>"Equatorial Guinea","language"=>"French","two_letter_code"=>"fr-GQ","three_letter_code"=>"fr-GNQ","locale_id"=>"4096"],
	["name"=>"Equatorial Guinea","language"=>"Portuguese","two_letter_code"=>"pt-GQ","three_letter_code"=>"pt-GNQ","locale_id"=>"4096"],
	["name"=>"Equatorial Guinea","language"=>"Spanish","two_letter_code"=>"es-GQ","three_letter_code"=>"es-GNQ","locale_id"=>"4096"],
	["name"=>"Eritrea","language"=>"Arabic","two_letter_code"=>"ar-ER","three_letter_code"=>"ar-ERI","locale_id"=>"4096"],
	["name"=>"Eritrea","language"=>"Blin","two_letter_code"=>"byn-ER","three_letter_code"=>"byn-ERI","locale_id"=>"4096"],
	["name"=>"Eritrea","language"=>"English","two_letter_code"=>"en-ER","three_letter_code"=>"en-ERI","locale_id"=>"4096"],
	["name"=>"Eritrea","language"=>"Geez","two_letter_code"=>"gez-ER","three_letter_code"=>"gez-ERI","locale_id"=>"4096"],
	["name"=>"Eritrea","language"=>"Tigre","two_letter_code"=>"tig-ER","three_letter_code"=>"tig-ERI","locale_id"=>"4096"],
	["name"=>"Eritrea","language"=>"Tigrinya","two_letter_code"=>"ti-ER","three_letter_code"=>"ti-ERI","locale_id"=>"2163"],
	["name"=>"Estonia","language"=>"English","two_letter_code"=>"en-EE","three_letter_code"=>"en-EST","locale_id"=>"4096"],
	["name"=>"Estonia","language"=>"Estonian","two_letter_code"=>"et-EE","three_letter_code"=>"et-EST","locale_id"=>"1061"],
	["name"=>"Eswatini","language"=>"English","two_letter_code"=>"en-SZ","three_letter_code"=>"en-SWZ","locale_id"=>"4096"],
	["name"=>"Eswatini","language"=>"Swati","two_letter_code"=>"ss-SZ","three_letter_code"=>"ss-SWZ","locale_id"=>"4096"],
	["name"=>"Ethiopia","language"=>"Amharic","two_letter_code"=>"am-ET","three_letter_code"=>"am-ETH","locale_id"=>"1118"],
	["name"=>"Ethiopia","language"=>"Geez","two_letter_code"=>"gez-ET","three_letter_code"=>"gez-ETH","locale_id"=>"4096"],
	["name"=>"Ethiopia","language"=>"Oromo","two_letter_code"=>"om-ET","three_letter_code"=>"om-ETH","locale_id"=>"1138"],
	["name"=>"Ethiopia","language"=>"Somali","two_letter_code"=>"so-ET","three_letter_code"=>"so-ETH","locale_id"=>"4096"],
	["name"=>"Ethiopia","language"=>"Tigrinya","two_letter_code"=>"ti-ET","three_letter_code"=>"ti-ETH","locale_id"=>"1139"],
	["name"=>"Ethiopia","language"=>"Wolaytta","two_letter_code"=>"wal-ET","three_letter_code"=>"wal-ETH","locale_id"=>"4096"],
	["name"=>"Europe","language"=>"English","two_letter_code"=>"en-150","three_letter_code"=>"en-","locale_id"=>"4096"],
	["name"=>"Falkland Islands","language"=>"English","two_letter_code"=>"en-FK","three_letter_code"=>"en-FLK","locale_id"=>"4096"],
	["name"=>"Falkland Islands","language"=>"Spanish","two_letter_code"=>"es-FK","three_letter_code"=>"es-FLK","locale_id"=>"4096"],
	["name"=>"Faroe Islands","language"=>"Faroese","two_letter_code"=>"fo-FO","three_letter_code"=>"fo-FRO","locale_id"=>"1080"],
	["name"=>"Fiji","language"=>"English","two_letter_code"=>"en-FJ","three_letter_code"=>"en-FJI","locale_id"=>"4096"],
	["name"=>"Finland","language"=>"English","two_letter_code"=>"en-FI","three_letter_code"=>"en-FIN","locale_id"=>"4096"],
	["name"=>"Finland","language"=>"Finnish","two_letter_code"=>"fi-FI","three_letter_code"=>"fi-FIN","locale_id"=>"1035"],
	["name"=>"Finland","language"=>"Inari Sami","two_letter_code"=>"smn-FI","three_letter_code"=>"smn-FIN","locale_id"=>"9275"],
	["name"=>"Finland","language"=>"Northern Sami","two_letter_code"=>"se-FI","three_letter_code"=>"se-FIN","locale_id"=>"3131"],
	["name"=>"Finland","language"=>"Swedish","two_letter_code"=>"sv-FI","three_letter_code"=>"sv-FIN","locale_id"=>"2077"],
	["name"=>"France","language"=>"Breton","two_letter_code"=>"br-FR","three_letter_code"=>"br-FRA","locale_id"=>"1150"],
	["name"=>"France","language"=>"Catalan","two_letter_code"=>"ca-FR","three_letter_code"=>"ca-FRA","locale_id"=>"4096"],
	["name"=>"France","language"=>"Corsican","two_letter_code"=>"co-FR","three_letter_code"=>"co-FRA","locale_id"=>"1155"],
	["name"=>"France","language"=>"English","two_letter_code"=>"en-FR","three_letter_code"=>"en-FRA","locale_id"=>"4096"],
	["name"=>"France","language"=>"French","two_letter_code"=>"fr-FR","three_letter_code"=>"fr-FRA","locale_id"=>"1036"],
	["name"=>"France","language"=>"Occitan","two_letter_code"=>"oc-FR","three_letter_code"=>"oc-FRA","locale_id"=>"1154"],
	["name"=>"France","language"=>"Portuguese","two_letter_code"=>"pt-FR","three_letter_code"=>"pt-FRA","locale_id"=>"4096"],
	["name"=>"France","language"=>"Swiss German","two_letter_code"=>"gsw-FR","three_letter_code"=>"gsw-FRA","locale_id"=>"1156"],
	["name"=>"French Guiana","language"=>"French","two_letter_code"=>"fr-GF","three_letter_code"=>"fr-GUF","locale_id"=>"4096"],
	["name"=>"French Guiana","language"=>"Spanish","two_letter_code"=>"es-GF","three_letter_code"=>"es-GUF","locale_id"=>"4096"],
	["name"=>"French Polynesia","language"=>"French","two_letter_code"=>"fr-PF","three_letter_code"=>"fr-PYF","locale_id"=>"4096"],
	["name"=>"Gabon","language"=>"French","two_letter_code"=>"fr-GA","three_letter_code"=>"fr-GAB","locale_id"=>"4096"],
	["name"=>"Gambia","language"=>"English","two_letter_code"=>"en-GM","three_letter_code"=>"en-GMB","locale_id"=>"4096"],
	["name"=>"Gambia","language"=>"Fulah","two_letter_code"=>"ff-GM","three_letter_code"=>"ff-GMB","locale_id"=>"4096"],
	["name"=>"Georgia","language"=>"Georgian","two_letter_code"=>"ka-GE","three_letter_code"=>"ka-GEO","locale_id"=>"1079"],
	["name"=>"Georgia","language"=>"Ossetic","two_letter_code"=>"os-GE","three_letter_code"=>"os-GEO","locale_id"=>"4096"],
	["name"=>"Germany","language"=>"Colognian","two_letter_code"=>"ksh-DE","three_letter_code"=>"ksh-DEU","locale_id"=>"4096"],
	["name"=>"Germany","language"=>"English","two_letter_code"=>"en-DE","three_letter_code"=>"en-DEU","locale_id"=>"4096"],
	["name"=>"Germany","language"=>"German","two_letter_code"=>"de-DE","three_letter_code"=>"de-DEU","locale_id"=>"1031"],
	["name"=>"Germany","language"=>"Low German","two_letter_code"=>"nds-DE","three_letter_code"=>"nds-DEU","locale_id"=>"4096"],
	["name"=>"Germany","language"=>"Lower Sorbian","two_letter_code"=>"dsb-DE","three_letter_code"=>"dsb-DEU","locale_id"=>"2094"],
	["name"=>"Germany","language"=>"Upper Sorbian","two_letter_code"=>"hsb-DE","three_letter_code"=>"hsb-DEU","locale_id"=>"1070"],
	["name"=>"Ghana","language"=>"Akan","two_letter_code"=>"ak-GH","three_letter_code"=>"ak-GHA","locale_id"=>"4096"],
	["name"=>"Ghana","language"=>"English","two_letter_code"=>"en-GH","three_letter_code"=>"en-GHA","locale_id"=>"4096"],
	["name"=>"Ghana","language"=>"Ewe","two_letter_code"=>"ee-GH","three_letter_code"=>"ee-GHA","locale_id"=>"4096"],
	["name"=>"Ghana","language"=>"Fulah","two_letter_code"=>"ff-GH","three_letter_code"=>"ff-GHA","locale_id"=>"4096"],
	["name"=>"Ghana","language"=>"Ga","two_letter_code"=>"gaa-GH","three_letter_code"=>"gaa-GHA","locale_id"=>"4096"],
	["name"=>"Ghana","language"=>"Hausa","two_letter_code"=>"ha-GH","three_letter_code"=>"ha-GHA","locale_id"=>"4096"],
	["name"=>"Gibraltar","language"=>"English","two_letter_code"=>"en-GI","three_letter_code"=>"en-GIB","locale_id"=>"4096"],
	["name"=>"Greece","language"=>"English","two_letter_code"=>"en-GR","three_letter_code"=>"en-GRC","locale_id"=>"4096"],
	["name"=>"Greece","language"=>"Greek","two_letter_code"=>"el-GR","three_letter_code"=>"el-GRC","locale_id"=>"1032"],
	["name"=>"Greenland","language"=>"Danish","two_letter_code"=>"da-GL","three_letter_code"=>"da-GRL","locale_id"=>"4096"],
	["name"=>"Greenland","language"=>"Kalaallisut","two_letter_code"=>"kl-GL","three_letter_code"=>"kl-GRL","locale_id"=>"1135"],
	["name"=>"Greenland","language"=>"Spanish","two_letter_code"=>"es-GL","three_letter_code"=>"es-GRL","locale_id"=>"4096"],
	["name"=>"Grenada","language"=>"English","two_letter_code"=>"en-GD","three_letter_code"=>"en-GRD","locale_id"=>"4096"],
	["name"=>"Grenada","language"=>"Spanish","two_letter_code"=>"es-GD","three_letter_code"=>"es-GRD","locale_id"=>"4096"],
	["name"=>"Guadeloupe","language"=>"French","two_letter_code"=>"fr-GP","three_letter_code"=>"fr-GLP","locale_id"=>"4096"],
	["name"=>"Guadeloupe","language"=>"Spanish","two_letter_code"=>"es-GP","three_letter_code"=>"es-GLP","locale_id"=>"4096"],
	["name"=>"Guam","language"=>"English","two_letter_code"=>"en-GU","three_letter_code"=>"en-GUM","locale_id"=>"4096"],
	["name"=>"Guatemala","language"=>"Spanish","two_letter_code"=>"es-GT","three_letter_code"=>"es-GTM","locale_id"=>"4106"],
	["name"=>"Guernsey","language"=>"English","two_letter_code"=>"en-GG","three_letter_code"=>"en-GGY","locale_id"=>"4096"],
	["name"=>"Guinea-Bissau","language"=>"Fulah","two_letter_code"=>"ff-GW","three_letter_code"=>"ff-GNB","locale_id"=>"4096"],
	["name"=>"Guinea-Bissau","language"=>"Portuguese","two_letter_code"=>"pt-GW","three_letter_code"=>"pt-GNB","locale_id"=>"4096"],
	["name"=>"Guinea","language"=>"French","two_letter_code"=>"fr-GN","three_letter_code"=>"fr-GIN","locale_id"=>"4096"],
	["name"=>"Guinea","language"=>"Fulah","two_letter_code"=>"ff-GN","three_letter_code"=>"ff-GIN","locale_id"=>"4096"],
	["name"=>"Guinea","language"=>"Kpelle","two_letter_code"=>"kpe-GN","three_letter_code"=>"kpe-GIN","locale_id"=>"4096"],
	["name"=>"Guinea","language"=>"N’Ko","two_letter_code"=>"nqo-GN","three_letter_code"=>"nqo-GIN","locale_id"=>"4096"],
	["name"=>"Guyana","language"=>"English","two_letter_code"=>"en-GY","three_letter_code"=>"en-GUY","locale_id"=>"4096"],
	["name"=>"Guyana","language"=>"Spanish","two_letter_code"=>"es-GY","three_letter_code"=>"es-GUY","locale_id"=>"4096"],
	["name"=>"Haiti","language"=>"French","two_letter_code"=>"fr-HT","three_letter_code"=>"fr-HTI","locale_id"=>"15372"],
	["name"=>"Haiti","language"=>"Spanish","two_letter_code"=>"es-HT","three_letter_code"=>"es-HTI","locale_id"=>"4096"],
	["name"=>"Honduras","language"=>"Spanish","two_letter_code"=>"es-HN","three_letter_code"=>"es-HND","locale_id"=>"18442"],
	["name"=>"Hong Kong","language"=>"Cantonese","two_letter_code"=>"yue-HK","three_letter_code"=>"yue-HKG","locale_id"=>"4096"],
	["name"=>"Hong Kong","language"=>"Chinese","two_letter_code"=>"zh-HK","three_letter_code"=>"zh-HKG","locale_id"=>"4096"],
	["name"=>"Hong Kong","language"=>"Chinese","two_letter_code"=>"zh-HK","three_letter_code"=>"zh-HKG","locale_id"=>"4096"],
	["name"=>"Hong Kong","language"=>"English","two_letter_code"=>"en-HK","three_letter_code"=>"en-HKG","locale_id"=>"15369"],
	["name"=>"Hungary","language"=>"English","two_letter_code"=>"en-HU","three_letter_code"=>"en-HUN","locale_id"=>"4096"],
	["name"=>"Hungary","language"=>"Hungarian","two_letter_code"=>"hu-HU","three_letter_code"=>"hu-HUN","locale_id"=>"1038"],
	["name"=>"Iceland","language"=>"English","two_letter_code"=>"en-IS","three_letter_code"=>"en-ISL","locale_id"=>"4096"],
	["name"=>"Iceland","language"=>"Icelandic","two_letter_code"=>"is-IS","three_letter_code"=>"is-ISL","locale_id"=>"1039"],
	["name"=>"India","language"=>"Assamese","two_letter_code"=>"as-IN","three_letter_code"=>"as-IND","locale_id"=>"1101"],
	["name"=>"India","language"=>"Bangla","two_letter_code"=>"bn-IN","three_letter_code"=>"bn-IND","locale_id"=>"1093"],
	["name"=>"India","language"=>"Bodo","two_letter_code"=>"brx-IN","three_letter_code"=>"brx-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Chakma","two_letter_code"=>"ccp-IN","three_letter_code"=>"ccp-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"English","two_letter_code"=>"en-IN","three_letter_code"=>"en-IND","locale_id"=>"16393"],
	["name"=>"India","language"=>"Gujarati","two_letter_code"=>"gu-IN","three_letter_code"=>"gu-IND","locale_id"=>"1095"],
	["name"=>"India","language"=>"Hindi","two_letter_code"=>"hi-IN","three_letter_code"=>"hi-IND","locale_id"=>"1081"],
	["name"=>"India","language"=>"Kannada","two_letter_code"=>"kn-IN","three_letter_code"=>"kn-IND","locale_id"=>"1099"],
	["name"=>"India","language"=>"Kashmiri","two_letter_code"=>"ks-IN","three_letter_code"=>"ks-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Kashmiri","two_letter_code"=>"ks-IN","three_letter_code"=>"ks-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Kashmiri","two_letter_code"=>"ks-IN","three_letter_code"=>"ks-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Konkani","two_letter_code"=>"kok-IN","three_letter_code"=>"kok-IND","locale_id"=>"1111"],
	["name"=>"India","language"=>"Malayalam","two_letter_code"=>"ml-IN","three_letter_code"=>"ml-IND","locale_id"=>"1100"],
	["name"=>"India","language"=>"Manipuri","two_letter_code"=>"mni-IN","three_letter_code"=>"mni-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Manipuri","two_letter_code"=>"mni-IN","three_letter_code"=>"mni-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Marathi","two_letter_code"=>"mr-IN","three_letter_code"=>"mr-IND","locale_id"=>"1102"],
	["name"=>"India","language"=>"Nepali","two_letter_code"=>"ne-IN","three_letter_code"=>"ne-IND","locale_id"=>"2145"],
	["name"=>"India","language"=>"Odia","two_letter_code"=>"or-IN","three_letter_code"=>"or-IND","locale_id"=>"1096"],
	["name"=>"India","language"=>"Punjabi","two_letter_code"=>"pa-IN","three_letter_code"=>"pa-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Sanskrit","two_letter_code"=>"sa-IN","three_letter_code"=>"sa-IND","locale_id"=>"1103"],
	["name"=>"India","language"=>"Santali","two_letter_code"=>"sat-IN","three_letter_code"=>"sat-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Santali","two_letter_code"=>"sat-IN","three_letter_code"=>"sat-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Tamil","two_letter_code"=>"ta-IN","three_letter_code"=>"ta-IND","locale_id"=>"1097"],
	["name"=>"India","language"=>"Telugu","two_letter_code"=>"te-IN","three_letter_code"=>"te-IND","locale_id"=>"1098"],
	["name"=>"India","language"=>"Tibetan","two_letter_code"=>"bo-IN","three_letter_code"=>"bo-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Urdu","two_letter_code"=>"ur-IN","three_letter_code"=>"ur-IND","locale_id"=>"2080"],
	["name"=>"India","language"=>"Urdu","two_letter_code"=>"ur-IN","three_letter_code"=>"ur-IND","locale_id"=>"4096"],
	["name"=>"India","language"=>"Urdu","two_letter_code"=>"ur-IN","three_letter_code"=>"ur-IND","locale_id"=>"4096"],
	["name"=>"Indonesia","language"=>"English","two_letter_code"=>"en-ID","three_letter_code"=>"en-IDN","locale_id"=>"14345"],
	["name"=>"Indonesia","language"=>"Indonesian","two_letter_code"=>"id-ID","three_letter_code"=>"id-IDN","locale_id"=>"1057"],
	["name"=>"Indonesia","language"=>"Javanese","two_letter_code"=>"jv-ID","three_letter_code"=>"jv-IDN","locale_id"=>"4096"],
	["name"=>"Iran","language"=>"Kurdish, Sorani","two_letter_code"=>"ckb-IR","three_letter_code"=>"ckb-IRN","locale_id"=>"4096"],
	["name"=>"Iran","language"=>"Mazanderani","two_letter_code"=>"mzn-IR","three_letter_code"=>"mzn-IRN","locale_id"=>"4096"],
	["name"=>"Iran","language"=>"Northern Luri","two_letter_code"=>"lrc-IR","three_letter_code"=>"lrc-IRN","locale_id"=>"4096"],
	["name"=>"Iran","language"=>"Persian","two_letter_code"=>"fa-IR","three_letter_code"=>"fa-IRN","locale_id"=>"1065"],
	["name"=>"Iraq","language"=>"Arabic","two_letter_code"=>"ar-IQ","three_letter_code"=>"ar-IRQ","locale_id"=>"2049"],
	["name"=>"Iraq","language"=>"Kurdish, Sorani","two_letter_code"=>"ckb-IQ","three_letter_code"=>"ckb-IRQ","locale_id"=>"4096"],
	["name"=>"Iraq","language"=>"Northern Luri","two_letter_code"=>"lrc-IQ","three_letter_code"=>"lrc-IRQ","locale_id"=>"4096"],
	["name"=>"Iraq","language"=>"Syriac","two_letter_code"=>"syr-IQ","three_letter_code"=>"syr-IRQ","locale_id"=>"4096"],
	["name"=>"Ireland","language"=>"English","two_letter_code"=>"en-IE","three_letter_code"=>"en-IRL","locale_id"=>"6153"],
	["name"=>"Ireland","language"=>"Irish","two_letter_code"=>"ga-IE","three_letter_code"=>"ga-IRL","locale_id"=>"2108"],
	["name"=>"Isle of Man","language"=>"English","two_letter_code"=>"en-IM","three_letter_code"=>"en-IMN","locale_id"=>"4096"],
	["name"=>"Isle of Man","language"=>"Manx","two_letter_code"=>"gv-IM","three_letter_code"=>"gv-IMN","locale_id"=>"4096"],
	["name"=>"Israel","language"=>"Arabic","two_letter_code"=>"ar-IL","three_letter_code"=>"ar-ISR","locale_id"=>"4096"],
	["name"=>"Israel","language"=>"English","two_letter_code"=>"en-IL","three_letter_code"=>"en-ISR","locale_id"=>"4096"],
	["name"=>"Israel","language"=>"Hebrew","two_letter_code"=>"he-IL","three_letter_code"=>"he-ISR","locale_id"=>"1037"],
	["name"=>"Italy","language"=>"Catalan","two_letter_code"=>"ca-IT","three_letter_code"=>"ca-ITA","locale_id"=>"4096"],
	["name"=>"Italy","language"=>"English","two_letter_code"=>"en-IT","three_letter_code"=>"en-ITA","locale_id"=>"4096"],
	["name"=>"Italy","language"=>"Friulian","two_letter_code"=>"fur-IT","three_letter_code"=>"fur-ITA","locale_id"=>"4096"],
	["name"=>"Italy","language"=>"German","two_letter_code"=>"de-IT","three_letter_code"=>"de-ITA","locale_id"=>"4096"],
	["name"=>"Italy","language"=>"Italian","two_letter_code"=>"it-IT","three_letter_code"=>"it-ITA","locale_id"=>"1040"],
	["name"=>"Italy","language"=>"Sardinian","two_letter_code"=>"sc-IT","three_letter_code"=>"sc-ITA","locale_id"=>"4096"],
	["name"=>"Italy","language"=>"Sicilian","two_letter_code"=>"scn-IT","three_letter_code"=>"scn-ITA","locale_id"=>"4096"],
	["name"=>"Jamaica","language"=>"English","two_letter_code"=>"en-JM","three_letter_code"=>"en-JAM","locale_id"=>"8201"],
	["name"=>"Japan","language"=>"English","two_letter_code"=>"en-JP","three_letter_code"=>"en-JPN","locale_id"=>"4096"],
	["name"=>"Japan","language"=>"Japanese","two_letter_code"=>"ja-JP","three_letter_code"=>"ja-JPN","locale_id"=>"1041"],
	["name"=>"Jersey","language"=>"English","two_letter_code"=>"en-JE","three_letter_code"=>"en-JEY","locale_id"=>"4096"],
	["name"=>"Jordan","language"=>"Arabic","two_letter_code"=>"ar-JO","three_letter_code"=>"ar-JOR","locale_id"=>"11265"],
	["name"=>"Kazakhstan","language"=>"Kazakh","two_letter_code"=>"kk-KZ","three_letter_code"=>"kk-KAZ","locale_id"=>"1087"],
	["name"=>"Kazakhstan","language"=>"Russian","two_letter_code"=>"ru-KZ","three_letter_code"=>"ru-KAZ","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Embu","two_letter_code"=>"ebu-KE","three_letter_code"=>"ebu-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"English","two_letter_code"=>"en-KE","three_letter_code"=>"en-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Gusii","two_letter_code"=>"guz-KE","three_letter_code"=>"guz-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Kalenjin","two_letter_code"=>"kln-KE","three_letter_code"=>"kln-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Kamba","two_letter_code"=>"kam-KE","three_letter_code"=>"kam-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Kikuyu","two_letter_code"=>"ki-KE","three_letter_code"=>"ki-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Luo","two_letter_code"=>"luo-KE","three_letter_code"=>"luo-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Luyia","two_letter_code"=>"luy-KE","three_letter_code"=>"luy-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Masai","two_letter_code"=>"mas-KE","three_letter_code"=>"mas-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Meru","two_letter_code"=>"mer-KE","three_letter_code"=>"mer-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Oromo","two_letter_code"=>"om-KE","three_letter_code"=>"om-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Samburu","two_letter_code"=>"saq-KE","three_letter_code"=>"saq-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Somali","two_letter_code"=>"so-KE","three_letter_code"=>"so-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Swahili","two_letter_code"=>"sw-KE","three_letter_code"=>"sw-KEN","locale_id"=>"1089"],
	["name"=>"Kenya","language"=>"Taita","two_letter_code"=>"dav-KE","three_letter_code"=>"dav-KEN","locale_id"=>"4096"],
	["name"=>"Kenya","language"=>"Teso","two_letter_code"=>"teo-KE","three_letter_code"=>"teo-KEN","locale_id"=>"4096"],
	["name"=>"Kiribati","language"=>"English","two_letter_code"=>"en-KI","three_letter_code"=>"en-KIR","locale_id"=>"4096"],
	["name"=>"Kosovo","language"=>"Albanian","two_letter_code"=>"sq-XK","three_letter_code"=>"sq-XKK","locale_id"=>"4096"],
	["name"=>"Kosovo","language"=>"Serbian","two_letter_code"=>"sr-XK","three_letter_code"=>"sr-XKK","locale_id"=>"4096"],
	["name"=>"Kosovo","language"=>"Serbian","two_letter_code"=>"sr-XK","three_letter_code"=>"sr-XKK","locale_id"=>"4096"],
	["name"=>"Kuwait","language"=>"Arabic","two_letter_code"=>"ar-KW","three_letter_code"=>"ar-KWT","locale_id"=>"13313"],
	["name"=>"Kyrgyzstan","language"=>"Kyrgyz","two_letter_code"=>"ky-KG","three_letter_code"=>"ky-KGZ","locale_id"=>"1088"],
	["name"=>"Kyrgyzstan","language"=>"Russian","two_letter_code"=>"ru-KG","three_letter_code"=>"ru-KGZ","locale_id"=>"4096"],
	["name"=>"Laos","language"=>"Lao","two_letter_code"=>"lo-LA","three_letter_code"=>"lo-LAO","locale_id"=>"1108"],
	["name"=>"Latin America","language"=>"Spanish","two_letter_code"=>"es-419","three_letter_code"=>"es-","locale_id"=>"22538"],
	["name"=>"Latvia","language"=>"English","two_letter_code"=>"en-LV","three_letter_code"=>"en-LVA","locale_id"=>"4096"],
	["name"=>"Latvia","language"=>"Latvian","two_letter_code"=>"lv-LV","three_letter_code"=>"lv-LVA","locale_id"=>"1062"],
	["name"=>"Lebanon","language"=>"Arabic","two_letter_code"=>"ar-LB","three_letter_code"=>"ar-LBN","locale_id"=>"12289"],
	["name"=>"Lesotho","language"=>"English","two_letter_code"=>"en-LS","three_letter_code"=>"en-LSO","locale_id"=>"4096"],
	["name"=>"Lesotho","language"=>"Southern Sotho","two_letter_code"=>"st-LS","three_letter_code"=>"st-LSO","locale_id"=>"4096"],
	["name"=>"Liberia","language"=>"English","two_letter_code"=>"en-LR","three_letter_code"=>"en-LBR","locale_id"=>"4096"],
	["name"=>"Liberia","language"=>"Fulah","two_letter_code"=>"ff-LR","three_letter_code"=>"ff-LBR","locale_id"=>"4096"],
	["name"=>"Liberia","language"=>"Kpelle","two_letter_code"=>"kpe-LR","three_letter_code"=>"kpe-LBR","locale_id"=>"4096"],
	["name"=>"Liberia","language"=>"Vai","two_letter_code"=>"vai-LR","three_letter_code"=>"vai-LBR","locale_id"=>"4096"],
	["name"=>"Liberia","language"=>"Vai","two_letter_code"=>"vai-LR","three_letter_code"=>"vai-LBR","locale_id"=>"4096"],
	["name"=>"Libya","language"=>"Arabic","two_letter_code"=>"ar-LY","three_letter_code"=>"ar-LBY","locale_id"=>"4097"],
	["name"=>"Liechtenstein","language"=>"German","two_letter_code"=>"de-LI","three_letter_code"=>"de-LIE","locale_id"=>"5127"],
	["name"=>"Liechtenstein","language"=>"Swiss German","two_letter_code"=>"gsw-LI","three_letter_code"=>"gsw-LIE","locale_id"=>"4096"],
	["name"=>"Lithuania","language"=>"English","two_letter_code"=>"en-LT","three_letter_code"=>"en-LTU","locale_id"=>"4096"],
	["name"=>"Lithuania","language"=>"Lithuanian","two_letter_code"=>"lt-LT","three_letter_code"=>"lt-LTU","locale_id"=>"1063"],
	["name"=>"Luxembourg","language"=>"English","two_letter_code"=>"en-LU","three_letter_code"=>"en-LUX","locale_id"=>"4096"],
	["name"=>"Luxembourg","language"=>"French","two_letter_code"=>"fr-LU","three_letter_code"=>"fr-LUX","locale_id"=>"5132"],
	["name"=>"Luxembourg","language"=>"German","two_letter_code"=>"de-LU","three_letter_code"=>"de-LUX","locale_id"=>"4103"],
	["name"=>"Luxembourg","language"=>"Luxembourgish","two_letter_code"=>"lb-LU","three_letter_code"=>"lb-LUX","locale_id"=>"1134"],
	["name"=>"Luxembourg","language"=>"Portuguese","two_letter_code"=>"pt-LU","three_letter_code"=>"pt-LUX","locale_id"=>"4096"],
	["name"=>"Macao","language"=>"Chinese","two_letter_code"=>"zh-MO","three_letter_code"=>"zh-MAC","locale_id"=>"4096"],
	["name"=>"Macao","language"=>"Chinese","two_letter_code"=>"zh-MO","three_letter_code"=>"zh-MAC","locale_id"=>"4096"],
	["name"=>"Macao","language"=>"English","two_letter_code"=>"en-MO","three_letter_code"=>"en-MAC","locale_id"=>"4096"],
	["name"=>"Macao","language"=>"Portuguese","two_letter_code"=>"pt-MO","three_letter_code"=>"pt-MAC","locale_id"=>"4096"],
	["name"=>"Madagascar","language"=>"English","two_letter_code"=>"en-MG","three_letter_code"=>"en-MDG","locale_id"=>"4096"],
	["name"=>"Madagascar","language"=>"French","two_letter_code"=>"fr-MG","three_letter_code"=>"fr-MDG","locale_id"=>"4096"],
	["name"=>"Madagascar","language"=>"Malagasy","two_letter_code"=>"mg-MG","three_letter_code"=>"mg-MDG","locale_id"=>"4096"],
	["name"=>"Malawi","language"=>"English","two_letter_code"=>"en-MW","three_letter_code"=>"en-MWI","locale_id"=>"4096"],
	["name"=>"Malawi","language"=>"Nyanja","two_letter_code"=>"ny-MW","three_letter_code"=>"ny-MWI","locale_id"=>"4096"],
	["name"=>"Malaysia","language"=>"English","two_letter_code"=>"en-MY","three_letter_code"=>"en-MYS","locale_id"=>"17417"],
	["name"=>"Malaysia","language"=>"Malay","two_letter_code"=>"ms-MY","three_letter_code"=>"ms-MYS","locale_id"=>"1086"],
	["name"=>"Malaysia","language"=>"Malay","two_letter_code"=>"ms-MY","three_letter_code"=>"ms-MYS","locale_id"=>"4096"],
	["name"=>"Malaysia","language"=>"Tamil","two_letter_code"=>"ta-MY","three_letter_code"=>"ta-MYS","locale_id"=>"4096"],
	["name"=>"Maldives","language"=>"Dhivehi","two_letter_code"=>"dv-MV","three_letter_code"=>"dv-MDV","locale_id"=>"1125"],
	["name"=>"Maldives","language"=>"English","two_letter_code"=>"en-MV","three_letter_code"=>"en-MDV","locale_id"=>"4096"],
	["name"=>"Mali","language"=>"Bambara","two_letter_code"=>"bm-ML","three_letter_code"=>"bm-MLI","locale_id"=>"4096"],
	["name"=>"Mali","language"=>"French","two_letter_code"=>"fr-ML","three_letter_code"=>"fr-MLI","locale_id"=>"13324"],
	["name"=>"Mali","language"=>"Koyra Chiini","two_letter_code"=>"khq-ML","three_letter_code"=>"khq-MLI","locale_id"=>"4096"],
	["name"=>"Mali","language"=>"Koyraboro Senni","two_letter_code"=>"ses-ML","three_letter_code"=>"ses-MLI","locale_id"=>"4096"],
	["name"=>"Malta","language"=>"English","two_letter_code"=>"en-MT","three_letter_code"=>"en-MLT","locale_id"=>"4096"],
	["name"=>"Malta","language"=>"Maltese","two_letter_code"=>"mt-MT","three_letter_code"=>"mt-MLT","locale_id"=>"1082"],
	["name"=>"Marshall Islands","language"=>"English","two_letter_code"=>"en-MH","three_letter_code"=>"en-MHL","locale_id"=>"4096"],
	["name"=>"Martinique","language"=>"French","two_letter_code"=>"fr-MQ","three_letter_code"=>"fr-MTQ","locale_id"=>"4096"],
	["name"=>"Martinique","language"=>"Spanish","two_letter_code"=>"es-MQ","three_letter_code"=>"es-MTQ","locale_id"=>"4096"],
	["name"=>"Mauritania","language"=>"Arabic","two_letter_code"=>"ar-MR","three_letter_code"=>"ar-MRT","locale_id"=>"4096"],
	["name"=>"Mauritania","language"=>"French","two_letter_code"=>"fr-MR","three_letter_code"=>"fr-MRT","locale_id"=>"4096"],
	["name"=>"Mauritania","language"=>"Fulah","two_letter_code"=>"ff-MR","three_letter_code"=>"ff-MRT","locale_id"=>"4096"],
	["name"=>"Mauritius","language"=>"English","two_letter_code"=>"en-MU","three_letter_code"=>"en-MUS","locale_id"=>"4096"],
	["name"=>"Mauritius","language"=>"French","two_letter_code"=>"fr-MU","three_letter_code"=>"fr-MUS","locale_id"=>"4096"],
	["name"=>"Mauritius","language"=>"Morisyen","two_letter_code"=>"mfe-MU","three_letter_code"=>"mfe-MUS","locale_id"=>"4096"],
	["name"=>"Mayotte","language"=>"French","two_letter_code"=>"fr-YT","three_letter_code"=>"fr-MYT","locale_id"=>"4096"],
	["name"=>"Mexico","language"=>"English","two_letter_code"=>"en-MX","three_letter_code"=>"en-MEX","locale_id"=>"4096"],
	["name"=>"Mexico","language"=>"Spanish","two_letter_code"=>"es-MX","three_letter_code"=>"es-MEX","locale_id"=>"2058"],
	["name"=>"Micronesia","language"=>"English","two_letter_code"=>"en-FM","three_letter_code"=>"en-FSM","locale_id"=>"4096"],
	["name"=>"Moldova","language"=>"Romanian","two_letter_code"=>"ro-MD","three_letter_code"=>"ro-MDA","locale_id"=>"2072"],
	["name"=>"Moldova","language"=>"Russian","two_letter_code"=>"ru-MD","three_letter_code"=>"ru-MDA","locale_id"=>"2073"],
	["name"=>"Monaco","language"=>"French","two_letter_code"=>"fr-MC","three_letter_code"=>"fr-MCO","locale_id"=>"6156"],
	["name"=>"Mongolia","language"=>"Mongolian","two_letter_code"=>"mn-MN","three_letter_code"=>"mn-MNG","locale_id"=>"1104"],
	["name"=>"Montenegro","language"=>"English","two_letter_code"=>"en-ME","three_letter_code"=>"en-MNE","locale_id"=>"4096"],
	["name"=>"Montenegro","language"=>"Serbian","two_letter_code"=>"sr-ME","three_letter_code"=>"sr-MNE","locale_id"=>"11290"],
	["name"=>"Montenegro","language"=>"Serbian","two_letter_code"=>"sr-ME","three_letter_code"=>"sr-MNE","locale_id"=>"12314"],
	["name"=>"Montserrat","language"=>"English","two_letter_code"=>"en-MS","three_letter_code"=>"en-MSR","locale_id"=>"4096"],
	["name"=>"Montserrat","language"=>"Spanish","two_letter_code"=>"es-MS","three_letter_code"=>"es-MSR","locale_id"=>"4096"],
	["name"=>"Morocco","language"=>"Arabic","two_letter_code"=>"ar-MA","three_letter_code"=>"ar-MAR","locale_id"=>"6145"],
	["name"=>"Morocco","language"=>"Central Atlas Tamazight","two_letter_code"=>"tzm-MA","three_letter_code"=>"tzm-MAR","locale_id"=>"4096"],
	["name"=>"Morocco","language"=>"French","two_letter_code"=>"fr-MA","three_letter_code"=>"fr-MAR","locale_id"=>"14348"],
	["name"=>"Morocco","language"=>"Standard Moroccan Tamazight","two_letter_code"=>"zgh-MA","three_letter_code"=>"zgh-MAR","locale_id"=>"4096"],
	["name"=>"Morocco","language"=>"Tachelhit","two_letter_code"=>"shi-MA","three_letter_code"=>"shi-MAR","locale_id"=>"4096"],
	["name"=>"Morocco","language"=>"Tachelhit","two_letter_code"=>"shi-MA","three_letter_code"=>"shi-MAR","locale_id"=>"4096"],
	["name"=>"Mozambique","language"=>"Makhuwa-Meetto","two_letter_code"=>"mgh-MZ","three_letter_code"=>"mgh-MOZ","locale_id"=>"4096"],
	["name"=>"Mozambique","language"=>"Portuguese","two_letter_code"=>"pt-MZ","three_letter_code"=>"pt-MOZ","locale_id"=>"4096"],
	["name"=>"Mozambique","language"=>"Sena","two_letter_code"=>"seh-MZ","three_letter_code"=>"seh-MOZ","locale_id"=>"4096"],
	["name"=>"Myanmar (Burma],","language"=>"Burmese","two_letter_code"=>"my-MM","three_letter_code"=>"my-MMR","locale_id"=>"1109"],
	["name"=>"Myanmar (Burma],","language"=>"English","two_letter_code"=>"en-MM","three_letter_code"=>"en-MMR","locale_id"=>"4096"],
	["name"=>"Namibia","language"=>"Afrikaans","two_letter_code"=>"af-NA","three_letter_code"=>"af-NAM","locale_id"=>"4096"],
	["name"=>"Namibia","language"=>"English","two_letter_code"=>"en-NA","three_letter_code"=>"en-NAM","locale_id"=>"4096"],
	["name"=>"Namibia","language"=>"Nama","two_letter_code"=>"naq-NA","three_letter_code"=>"naq-NAM","locale_id"=>"4096"],
	["name"=>"Nauru","language"=>"English","two_letter_code"=>"en-NR","three_letter_code"=>"en-NRU","locale_id"=>"4096"],
	["name"=>"Nepal","language"=>"Nepali","two_letter_code"=>"ne-NP","three_letter_code"=>"ne-NPL","locale_id"=>"1121"],
	["name"=>"Netherlands","language"=>"Dutch","two_letter_code"=>"nl-NL","three_letter_code"=>"nl-NLD","locale_id"=>"1043"],
	["name"=>"Netherlands","language"=>"English","two_letter_code"=>"en-NL","three_letter_code"=>"en-NLD","locale_id"=>"4096"],
	["name"=>"Netherlands","language"=>"Low German","two_letter_code"=>"nds-NL","three_letter_code"=>"nds-NLD","locale_id"=>"4096"],
	["name"=>"Netherlands","language"=>"Western Frisian","two_letter_code"=>"fy-NL","three_letter_code"=>"fy-NLD","locale_id"=>"1122"],
	["name"=>"New Caledonia","language"=>"French","two_letter_code"=>"fr-NC","three_letter_code"=>"fr-NCL","locale_id"=>"4096"],
	["name"=>"New Zealand","language"=>"English","two_letter_code"=>"en-NZ","three_letter_code"=>"en-NZL","locale_id"=>"5129"],
	["name"=>"New Zealand","language"=>"Maori","two_letter_code"=>"mi-NZ","three_letter_code"=>"mi-NZL","locale_id"=>"1153"],
	["name"=>"Nicaragua","language"=>"Spanish","two_letter_code"=>"es-NI","three_letter_code"=>"es-NIC","locale_id"=>"19466"],
	["name"=>"Niger","language"=>"French","two_letter_code"=>"fr-NE","three_letter_code"=>"fr-NER","locale_id"=>"4096"],
	["name"=>"Niger","language"=>"Fulah","two_letter_code"=>"ff-NE","three_letter_code"=>"ff-NER","locale_id"=>"4096"],
	["name"=>"Niger","language"=>"Hausa","two_letter_code"=>"ha-NE","three_letter_code"=>"ha-NER","locale_id"=>"4096"],
	["name"=>"Niger","language"=>"Tasawaq","two_letter_code"=>"twq-NE","three_letter_code"=>"twq-NER","locale_id"=>"4096"],
	["name"=>"Niger","language"=>"Zarma","two_letter_code"=>"dje-NE","three_letter_code"=>"dje-NER","locale_id"=>"4096"],
	["name"=>"Nigeria","language"=>"English","two_letter_code"=>"en-NG","three_letter_code"=>"en-NGA","locale_id"=>"4096"],
	["name"=>"Nigeria","language"=>"Fulah","two_letter_code"=>"ff-NG","three_letter_code"=>"ff-NGA","locale_id"=>"4096"],
	["name"=>"Nigeria","language"=>"Hausa","two_letter_code"=>"ha-NG","three_letter_code"=>"ha-NGA","locale_id"=>"4096"],
	["name"=>"Nigeria","language"=>"Igbo","two_letter_code"=>"ig-NG","three_letter_code"=>"ig-NGA","locale_id"=>"1136"],
	["name"=>"Nigeria","language"=>"Jju","two_letter_code"=>"kaj-NG","three_letter_code"=>"kaj-NGA","locale_id"=>"4096"],
	["name"=>"Nigeria","language"=>"Tyap","two_letter_code"=>"kcg-NG","three_letter_code"=>"kcg-NGA","locale_id"=>"4096"],
	["name"=>"Nigeria","language"=>"Yoruba","two_letter_code"=>"yo-NG","three_letter_code"=>"yo-NGA","locale_id"=>"1130"],
	["name"=>"Niue","language"=>"English","two_letter_code"=>"en-NU","three_letter_code"=>"en-NIU","locale_id"=>"4096"],
	["name"=>"Norfolk Island","language"=>"English","two_letter_code"=>"en-NF","three_letter_code"=>"en-NFK","locale_id"=>"4096"],
	["name"=>"North Korea","language"=>"Korean","two_letter_code"=>"ko-KP","three_letter_code"=>"ko-PRK","locale_id"=>"4096"],
	["name"=>"North Macedonia","language"=>"Albanian","two_letter_code"=>"sq-MK","three_letter_code"=>"sq-MKD","locale_id"=>"4096"],
	["name"=>"North Macedonia","language"=>"Macedonian","two_letter_code"=>"mk-MK","three_letter_code"=>"mk-MKD","locale_id"=>"1071"],
	["name"=>"Northern Mariana Islands","language"=>"English","two_letter_code"=>"en-MP","three_letter_code"=>"en-MNP","locale_id"=>"4096"],
	["name"=>"Norway","language"=>"English","two_letter_code"=>"en-NO","three_letter_code"=>"en-NOR","locale_id"=>"4096"],
	["name"=>"Norway","language"=>"Northern Sami","two_letter_code"=>"se-NO","three_letter_code"=>"se-NOR","locale_id"=>"1083"],
	["name"=>"Norway","language"=>"Norwegian Bokmål","two_letter_code"=>"nb-NO","three_letter_code"=>"nb-NOR","locale_id"=>"1044"],
	["name"=>"Norway","language"=>"Norwegian Nynorsk","two_letter_code"=>"nn-NO","three_letter_code"=>"nn-NOR","locale_id"=>"2068"],
	["name"=>"Oman","language"=>"Arabic","two_letter_code"=>"ar-OM","three_letter_code"=>"ar-OMN","locale_id"=>"8193"],
	["name"=>"Pakistan","language"=>"English","two_letter_code"=>"en-PK","three_letter_code"=>"en-PAK","locale_id"=>"4096"],
	["name"=>"Pakistan","language"=>"Pashto","two_letter_code"=>"ps-PK","three_letter_code"=>"ps-PAK","locale_id"=>"4096"],
	["name"=>"Pakistan","language"=>"Punjabi","two_letter_code"=>"pa-PK","three_letter_code"=>"pa-PAK","locale_id"=>"2118"],
	["name"=>"Pakistan","language"=>"Punjabi","two_letter_code"=>"pa-PK","three_letter_code"=>"pa-PAK","locale_id"=>"4096"],
	["name"=>"Pakistan","language"=>"Sindhi","two_letter_code"=>"sd-PK","three_letter_code"=>"sd-PAK","locale_id"=>"4096"],
	["name"=>"Pakistan","language"=>"Urdu","two_letter_code"=>"ur-PK","three_letter_code"=>"ur-PAK","locale_id"=>"1056"],
	["name"=>"Pakistan","language"=>"Urdu","two_letter_code"=>"ur-PK","three_letter_code"=>"ur-PAK","locale_id"=>"4096"],
	["name"=>"Pakistan","language"=>"Urdu","two_letter_code"=>"ur-PK","three_letter_code"=>"ur-PAK","locale_id"=>"4096"],
	["name"=>"Palau","language"=>"English","two_letter_code"=>"en-PW","three_letter_code"=>"en-PLW","locale_id"=>"4096"],
	["name"=>"Palestinian Territories","language"=>"Arabic","two_letter_code"=>"ar-PS","three_letter_code"=>"ar-PSE","locale_id"=>"4096"],
	["name"=>"Panama","language"=>"Spanish","two_letter_code"=>"es-PA","three_letter_code"=>"es-PAN","locale_id"=>"6154"],
	["name"=>"Papua New Guinea","language"=>"English","two_letter_code"=>"en-PG","three_letter_code"=>"en-PNG","locale_id"=>"4096"],
	["name"=>"Paraguay","language"=>"Guarani","two_letter_code"=>"gn-PY","three_letter_code"=>"gn-PRY","locale_id"=>"1140"],
	["name"=>"Paraguay","language"=>"Spanish","two_letter_code"=>"es-PY","three_letter_code"=>"es-PRY","locale_id"=>"15370"],
	["name"=>"Peru","language"=>"Quechua","two_letter_code"=>"qu-PE","three_letter_code"=>"qu-PER","locale_id"=>"4096"],
	["name"=>"Peru","language"=>"Spanish","two_letter_code"=>"es-PE","three_letter_code"=>"es-PER","locale_id"=>"10250"],
	["name"=>"Philippines","language"=>"Cebuano","two_letter_code"=>"ceb-PH","three_letter_code"=>"ceb-PHL","locale_id"=>"4096"],
	["name"=>"Philippines","language"=>"English","two_letter_code"=>"en-PH","three_letter_code"=>"en-PHL","locale_id"=>"13321"],
	["name"=>"Philippines","language"=>"Filipino","two_letter_code"=>"fil-PH","three_letter_code"=>"fil-PHL","locale_id"=>"1124"],
	["name"=>"Philippines","language"=>"Spanish","two_letter_code"=>"es-PH","three_letter_code"=>"es-PHL","locale_id"=>"4096"],
	["name"=>"Pitcairn Islands","language"=>"English","two_letter_code"=>"en-PN","three_letter_code"=>"en-PCN","locale_id"=>"4096"],
	["name"=>"Poland","language"=>"English","two_letter_code"=>"en-PL","three_letter_code"=>"en-POL","locale_id"=>"4096"],
	["name"=>"Poland","language"=>"Polish","two_letter_code"=>"pl-PL","three_letter_code"=>"pl-POL","locale_id"=>"1045"],
	["name"=>"Portugal","language"=>"English","two_letter_code"=>"en-PT","three_letter_code"=>"en-PRT","locale_id"=>"4096"],
	["name"=>"Portugal","language"=>"Portuguese","two_letter_code"=>"pt-PT","three_letter_code"=>"pt-PRT","locale_id"=>"2070"],
	["name"=>"Puerto Rico","language"=>"English","two_letter_code"=>"en-PR","three_letter_code"=>"en-PRI","locale_id"=>"4096"],
	["name"=>"Puerto Rico","language"=>"Spanish","two_letter_code"=>"es-PR","three_letter_code"=>"es-PRI","locale_id"=>"20490"],
	["name"=>"Qatar","language"=>"Arabic","two_letter_code"=>"ar-QA","three_letter_code"=>"ar-QAT","locale_id"=>"16385"],
	["name"=>"Réunion","language"=>"French","two_letter_code"=>"fr-RE","three_letter_code"=>"fr-REU","locale_id"=>"8204"],
	["name"=>"Romania","language"=>"English","two_letter_code"=>"en-RO","three_letter_code"=>"en-ROU","locale_id"=>"4096"],
	["name"=>"Romania","language"=>"Romanian","two_letter_code"=>"ro-RO","three_letter_code"=>"ro-ROU","locale_id"=>"1048"],
	["name"=>"Russia","language"=>"Bashkir","two_letter_code"=>"ba-RU","three_letter_code"=>"ba-RUS","locale_id"=>"1133"],
	["name"=>"Russia","language"=>"Chechen","two_letter_code"=>"ce-RU","three_letter_code"=>"ce-RUS","locale_id"=>"4096"],
	["name"=>"Russia","language"=>"Chuvash","two_letter_code"=>"cv-RU","three_letter_code"=>"cv-RUS","locale_id"=>"4096"],
	["name"=>"Russia","language"=>"English","two_letter_code"=>"en-RU","three_letter_code"=>"en-RUS","locale_id"=>"4096"],
	["name"=>"Russia","language"=>"Erzya","two_letter_code"=>"myv-RU","three_letter_code"=>"myv-RUS","locale_id"=>"4096"],
	["name"=>"Russia","language"=>"Ossetic","two_letter_code"=>"os-RU","three_letter_code"=>"os-RUS","locale_id"=>"4096"],
	["name"=>"Russia","language"=>"Russian","two_letter_code"=>"ru-RU","three_letter_code"=>"ru-RUS","locale_id"=>"1049"],
	["name"=>"Russia","language"=>"Sakha","two_letter_code"=>"sah-RU","three_letter_code"=>"sah-RUS","locale_id"=>"1157"],
	["name"=>"Russia","language"=>"Tatar","two_letter_code"=>"tt-RU","three_letter_code"=>"tt-RUS","locale_id"=>"1092"],
	["name"=>"Rwanda","language"=>"English","two_letter_code"=>"en-RW","three_letter_code"=>"en-RWA","locale_id"=>"4096"],
	["name"=>"Rwanda","language"=>"French","two_letter_code"=>"fr-RW","three_letter_code"=>"fr-RWA","locale_id"=>"4096"],
	["name"=>"Rwanda","language"=>"Kinyarwanda","two_letter_code"=>"rw-RW","three_letter_code"=>"rw-RWA","locale_id"=>"1159"],
	["name"=>"Samoa","language"=>"English","two_letter_code"=>"en-WS","three_letter_code"=>"en-WSM","locale_id"=>"4096"],
	["name"=>"San Marino","language"=>"Italian","two_letter_code"=>"it-SM","three_letter_code"=>"it-SMR","locale_id"=>"4096"],
	["name"=>"São Tomé &amp; Príncipe","language"=>"Portuguese","two_letter_code"=>"pt-ST","three_letter_code"=>"pt-STP","locale_id"=>"4096"],
	["name"=>"Saudi Arabia","language"=>"Arabic","two_letter_code"=>"ar-SA","three_letter_code"=>"ar-SAU","locale_id"=>"1025"],
	["name"=>"Saudi Arabia","language"=>"English","two_letter_code"=>"en-SA","three_letter_code"=>"en-SAU","locale_id"=>"4096"],
	["name"=>"Senegal","language"=>"French","two_letter_code"=>"fr-SN","three_letter_code"=>"fr-SEN","locale_id"=>"10252"],
	["name"=>"Senegal","language"=>"Fulah","two_letter_code"=>"ff-SN","three_letter_code"=>"ff-SEN","locale_id"=>"2151"],
	["name"=>"Senegal","language"=>"Jola-Fonyi","two_letter_code"=>"dyo-SN","three_letter_code"=>"dyo-SEN","locale_id"=>"4096"],
	["name"=>"Senegal","language"=>"Wolof","two_letter_code"=>"wo-SN","three_letter_code"=>"wo-SEN","locale_id"=>"1160"],
	["name"=>"Serbia","language"=>"English","two_letter_code"=>"en-RS","three_letter_code"=>"en-SRB","locale_id"=>"4096"],
	["name"=>"Serbia","language"=>"Serbian","two_letter_code"=>"sr-RS","three_letter_code"=>"sr-SRB","locale_id"=>"10266"],
	["name"=>"Serbia","language"=>"Serbian","two_letter_code"=>"sr-RS","three_letter_code"=>"sr-SRB","locale_id"=>"9242"],
	["name"=>"Seychelles","language"=>"English","two_letter_code"=>"en-SC","three_letter_code"=>"en-SYC","locale_id"=>"4096"],
	["name"=>"Seychelles","language"=>"French","two_letter_code"=>"fr-SC","three_letter_code"=>"fr-SYC","locale_id"=>"4096"],
	["name"=>"Sierra Leone","language"=>"English","two_letter_code"=>"en-SL","three_letter_code"=>"en-SLE","locale_id"=>"4096"],
	["name"=>"Sierra Leone","language"=>"Fulah","two_letter_code"=>"ff-SL","three_letter_code"=>"ff-SLE","locale_id"=>"4096"],
	["name"=>"Singapore","language"=>"Chinese","two_letter_code"=>"zh-SG","three_letter_code"=>"zh-SGP","locale_id"=>"4096"],
	["name"=>"Singapore","language"=>"English","two_letter_code"=>"en-SG","three_letter_code"=>"en-SGP","locale_id"=>"18441"],
	["name"=>"Singapore","language"=>"Malay","two_letter_code"=>"ms-SG","three_letter_code"=>"ms-SGP","locale_id"=>"4096"],
	["name"=>"Singapore","language"=>"Tamil","two_letter_code"=>"ta-SG","three_letter_code"=>"ta-SGP","locale_id"=>"4096"],
	["name"=>"Sint Maarten","language"=>"Dutch","two_letter_code"=>"nl-SX","three_letter_code"=>"nl-SXM","locale_id"=>"4096"],
	["name"=>"Sint Maarten","language"=>"English","two_letter_code"=>"en-SX","three_letter_code"=>"en-SXM","locale_id"=>"4096"],
	["name"=>"Sint Maarten","language"=>"Spanish","two_letter_code"=>"es-SX","three_letter_code"=>"es-SXM","locale_id"=>"4096"],
	["name"=>"Slovakia","language"=>"English","two_letter_code"=>"en-SK","three_letter_code"=>"en-SVK","locale_id"=>"4096"],
	["name"=>"Slovakia","language"=>"Slovak","two_letter_code"=>"sk-SK","three_letter_code"=>"sk-SVK","locale_id"=>"1051"],
	["name"=>"Slovenia","language"=>"English","two_letter_code"=>"en-SI","three_letter_code"=>"en-SVN","locale_id"=>"4096"],
	["name"=>"Slovenia","language"=>"Slovenian","two_letter_code"=>"sl-SI","three_letter_code"=>"sl-SVN","locale_id"=>"1060"],
	["name"=>"Solomon Islands","language"=>"English","two_letter_code"=>"en-SB","three_letter_code"=>"en-SLB","locale_id"=>"4096"],
	["name"=>"Somalia","language"=>"Arabic","two_letter_code"=>"ar-SO","three_letter_code"=>"ar-SOM","locale_id"=>"4096"],
	["name"=>"Somalia","language"=>"Somali","two_letter_code"=>"so-SO","three_letter_code"=>"so-SOM","locale_id"=>"1143"],
	["name"=>"South Africa","language"=>"Afrikaans","two_letter_code"=>"af-ZA","three_letter_code"=>"af-ZAF","locale_id"=>"1078"],
	["name"=>"South Africa","language"=>"English","two_letter_code"=>"en-ZA","three_letter_code"=>"en-ZAF","locale_id"=>"7177"],
	["name"=>"South Africa","language"=>"Northern Sotho","two_letter_code"=>"nso-ZA","three_letter_code"=>"nso-ZAF","locale_id"=>"1132"],
	["name"=>"South Africa","language"=>"South Ndebele","two_letter_code"=>"nr-ZA","three_letter_code"=>"nr-ZAF","locale_id"=>"4096"],
	["name"=>"South Africa","language"=>"Southern Sotho","two_letter_code"=>"st-ZA","three_letter_code"=>"st-ZAF","locale_id"=>"1072"],
	["name"=>"South Africa","language"=>"Swati","two_letter_code"=>"ss-ZA","three_letter_code"=>"ss-ZAF","locale_id"=>"4096"],
	["name"=>"South Africa","language"=>"Tsonga","two_letter_code"=>"ts-ZA","three_letter_code"=>"ts-ZAF","locale_id"=>"1073"],
	["name"=>"South Africa","language"=>"Tswana","two_letter_code"=>"tn-ZA","three_letter_code"=>"tn-ZAF","locale_id"=>"1074"],
	["name"=>"South Africa","language"=>"Venda","two_letter_code"=>"ve-ZA","three_letter_code"=>"ve-ZAF","locale_id"=>"1075"],
	["name"=>"South Africa","language"=>"Xhosa","two_letter_code"=>"xh-ZA","three_letter_code"=>"xh-ZAF","locale_id"=>"1076"],
	["name"=>"South Africa","language"=>"Zulu","two_letter_code"=>"zu-ZA","three_letter_code"=>"zu-ZAF","locale_id"=>"1077"],
	["name"=>"South Korea","language"=>"English","two_letter_code"=>"en-KR","three_letter_code"=>"en-KOR","locale_id"=>"4096"],
	["name"=>"South Korea","language"=>"Korean","two_letter_code"=>"ko-KR","three_letter_code"=>"ko-KOR","locale_id"=>"1042"],
	["name"=>"South Sudan","language"=>"Arabic","two_letter_code"=>"ar-SS","three_letter_code"=>"ar-SSD","locale_id"=>"4096"],
	["name"=>"South Sudan","language"=>"English","two_letter_code"=>"en-SS","three_letter_code"=>"en-SSD","locale_id"=>"4096"],
	["name"=>"South Sudan","language"=>"Nuer","two_letter_code"=>"nus-SS","three_letter_code"=>"nus-SSD","locale_id"=>"4096"],
	["name"=>"Spain","language"=>"Asturian","two_letter_code"=>"ast-ES","three_letter_code"=>"ast-ESP","locale_id"=>"4096"],
	["name"=>"Spain","language"=>"Basque","two_letter_code"=>"eu-ES","three_letter_code"=>"eu-ESP","locale_id"=>"1069"],
	["name"=>"Spain","language"=>"Catalan","two_letter_code"=>"ca-ES","three_letter_code"=>"ca-ESP","locale_id"=>"1027"],
	["name"=>"Spain","language"=>"English","two_letter_code"=>"en-ES","three_letter_code"=>"en-ESP","locale_id"=>"4096"],
	["name"=>"Spain","language"=>"Galician","two_letter_code"=>"gl-ES","three_letter_code"=>"gl-ESP","locale_id"=>"1110"],
	["name"=>"Spain","language"=>"Spanish","two_letter_code"=>"es-ES","three_letter_code"=>"es-ESP","locale_id"=>"3082"],
	["name"=>"Sri Lanka","language"=>"Sinhala","two_letter_code"=>"si-LK","three_letter_code"=>"si-LKA","locale_id"=>"1115"],
	["name"=>"Sri Lanka","language"=>"Tamil","two_letter_code"=>"ta-LK","three_letter_code"=>"ta-LKA","locale_id"=>"2121"],
	["name"=>"St. Barthélemy","language"=>"French","two_letter_code"=>"fr-BL","three_letter_code"=>"fr-BLM","locale_id"=>"4096"],
	["name"=>"St. Barthélemy","language"=>"Spanish","two_letter_code"=>"es-BL","three_letter_code"=>"es-BLM","locale_id"=>"4096"],
	["name"=>"St. Helena","language"=>"English","two_letter_code"=>"en-SH","three_letter_code"=>"en-SHN","locale_id"=>"4096"],
	["name"=>"St. Kitts &amp; Nevis","language"=>"English","two_letter_code"=>"en-KN","three_letter_code"=>"en-KNA","locale_id"=>"4096"],
	["name"=>"St. Kitts &amp; Nevis","language"=>"Spanish","two_letter_code"=>"es-KN","three_letter_code"=>"es-KNA","locale_id"=>"4096"],
	["name"=>"St. Lucia","language"=>"English","two_letter_code"=>"en-LC","three_letter_code"=>"en-LCA","locale_id"=>"4096"],
	["name"=>"St. Lucia","language"=>"Spanish","two_letter_code"=>"es-LC","three_letter_code"=>"es-LCA","locale_id"=>"4096"],
	["name"=>"St. Martin","language"=>"French","two_letter_code"=>"fr-MF","three_letter_code"=>"fr-MAF","locale_id"=>"4096"],
	["name"=>"St. Martin","language"=>"Spanish","two_letter_code"=>"es-MF","three_letter_code"=>"es-MAF","locale_id"=>"4096"],
	["name"=>"St. Pierre &amp; Miquelon","language"=>"French","two_letter_code"=>"fr-PM","three_letter_code"=>"fr-SPM","locale_id"=>"4096"],
	["name"=>"St. Pierre &amp; Miquelon","language"=>"Spanish","two_letter_code"=>"es-PM","three_letter_code"=>"es-SPM","locale_id"=>"4096"],
	["name"=>"St. Vincent &amp; Grenadines","language"=>"English","two_letter_code"=>"en-VC","three_letter_code"=>"en-VCT","locale_id"=>"4096"],
	["name"=>"St. Vincent &amp; Grenadines","language"=>"Spanish","two_letter_code"=>"es-VC","three_letter_code"=>"es-VCT","locale_id"=>"4096"],
	["name"=>"Sudan","language"=>"Arabic","two_letter_code"=>"ar-SD","three_letter_code"=>"ar-SDN","locale_id"=>"4096"],
	["name"=>"Sudan","language"=>"English","two_letter_code"=>"en-SD","three_letter_code"=>"en-SDN","locale_id"=>"4096"],
	["name"=>"Suriname","language"=>"Dutch","two_letter_code"=>"nl-SR","three_letter_code"=>"nl-SUR","locale_id"=>"4096"],
	["name"=>"Suriname","language"=>"Spanish","two_letter_code"=>"es-SR","three_letter_code"=>"es-SUR","locale_id"=>"4096"],
	["name"=>"Svalbard &amp; Jan Mayen","language"=>"Norwegian Bokmål","two_letter_code"=>"nb-SJ","three_letter_code"=>"nb-SJM","locale_id"=>"4096"],
	["name"=>"Sweden","language"=>"English","two_letter_code"=>"en-SE","three_letter_code"=>"en-SWE","locale_id"=>"4096"],
	["name"=>"Sweden","language"=>"Northern Sami","two_letter_code"=>"se-SE","three_letter_code"=>"se-SWE","locale_id"=>"2107"],
	["name"=>"Sweden","language"=>"Swedish","two_letter_code"=>"sv-SE","three_letter_code"=>"sv-SWE","locale_id"=>"1053"],
	["name"=>"Switzerland","language"=>"English","two_letter_code"=>"en-CH","three_letter_code"=>"en-CHE","locale_id"=>"4096"],
	["name"=>"Switzerland","language"=>"French","two_letter_code"=>"fr-CH","three_letter_code"=>"fr-CHE","locale_id"=>"4108"],
	["name"=>"Switzerland","language"=>"German","two_letter_code"=>"de-CH","three_letter_code"=>"de-CHE","locale_id"=>"2055"],
	["name"=>"Switzerland","language"=>"Italian","two_letter_code"=>"it-CH","three_letter_code"=>"it-CHE","locale_id"=>"2064"],
	["name"=>"Switzerland","language"=>"Portuguese","two_letter_code"=>"pt-CH","three_letter_code"=>"pt-CHE","locale_id"=>"4096"],
	["name"=>"Switzerland","language"=>"Romansh","two_letter_code"=>"rm-CH","three_letter_code"=>"rm-CHE","locale_id"=>"1047"],
	["name"=>"Switzerland","language"=>"Swiss German","two_letter_code"=>"gsw-CH","three_letter_code"=>"gsw-CHE","locale_id"=>"4096"],
	["name"=>"Switzerland","language"=>"Walser","two_letter_code"=>"wae-CH","three_letter_code"=>"wae-CHE","locale_id"=>"4096"],
	["name"=>"Syria","language"=>"Arabic","two_letter_code"=>"ar-SY","three_letter_code"=>"ar-SYR","locale_id"=>"10241"],
	["name"=>"Syria","language"=>"French","two_letter_code"=>"fr-SY","three_letter_code"=>"fr-SYR","locale_id"=>"4096"],
	["name"=>"Syria","language"=>"Syriac","two_letter_code"=>"syr-SY","three_letter_code"=>"syr-SYR","locale_id"=>"1114"],
	["name"=>"Taiwan","language"=>"Chinese","two_letter_code"=>"zh-TW","three_letter_code"=>"zh-TWN","locale_id"=>"4096"],
	["name"=>"Taiwan","language"=>"English","two_letter_code"=>"en-TW","three_letter_code"=>"en-TWN","locale_id"=>"4096"],
	["name"=>"Taiwan","language"=>"Taroko","two_letter_code"=>"trv-TW","three_letter_code"=>"trv-TWN","locale_id"=>"4096"],
	["name"=>"Tajikistan","language"=>"Tajik","two_letter_code"=>"tg-TJ","three_letter_code"=>"tg-TJK","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Asu","two_letter_code"=>"asa-TZ","three_letter_code"=>"asa-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Bena","two_letter_code"=>"bez-TZ","three_letter_code"=>"bez-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"English","two_letter_code"=>"en-TZ","three_letter_code"=>"en-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Langi","two_letter_code"=>"lag-TZ","three_letter_code"=>"lag-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Machame","two_letter_code"=>"jmc-TZ","three_letter_code"=>"jmc-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Makonde","two_letter_code"=>"kde-TZ","three_letter_code"=>"kde-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Masai","two_letter_code"=>"mas-TZ","three_letter_code"=>"mas-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Rombo","two_letter_code"=>"rof-TZ","three_letter_code"=>"rof-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Rwa","two_letter_code"=>"rwk-TZ","three_letter_code"=>"rwk-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Sangu","two_letter_code"=>"sbp-TZ","three_letter_code"=>"sbp-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Shambala","two_letter_code"=>"ksb-TZ","three_letter_code"=>"ksb-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Swahili","two_letter_code"=>"sw-TZ","three_letter_code"=>"sw-TZA","locale_id"=>"4096"],
	["name"=>"Tanzania","language"=>"Vunjo","two_letter_code"=>"vun-TZ","three_letter_code"=>"vun-TZA","locale_id"=>"4096"],
	["name"=>"Thailand","language"=>"English","two_letter_code"=>"en-TH","three_letter_code"=>"en-THA","locale_id"=>"4096"],
	["name"=>"Thailand","language"=>"Thai","two_letter_code"=>"th-TH","three_letter_code"=>"th-THA","locale_id"=>"1054"],
	["name"=>"Timor-Leste","language"=>"Portuguese","two_letter_code"=>"pt-TL","three_letter_code"=>"pt-TLS","locale_id"=>"4096"],
	["name"=>"Togo","language"=>"Ewe","two_letter_code"=>"ee-TG","three_letter_code"=>"ee-TGO","locale_id"=>"4096"],
	["name"=>"Togo","language"=>"French","two_letter_code"=>"fr-TG","three_letter_code"=>"fr-TGO","locale_id"=>"4096"],
	["name"=>"Tokelau","language"=>"English","two_letter_code"=>"en-TK","three_letter_code"=>"en-TKL","locale_id"=>"4096"],
	["name"=>"Tonga","language"=>"English","two_letter_code"=>"en-TO","three_letter_code"=>"en-TON","locale_id"=>"4096"],
	["name"=>"Tonga","language"=>"Tongan","two_letter_code"=>"to-TO","three_letter_code"=>"to-TON","locale_id"=>"4096"],
	["name"=>"Trinidad &amp; Tobago","language"=>"English","two_letter_code"=>"en-TT","three_letter_code"=>"en-TTO","locale_id"=>"11273"],
	["name"=>"Trinidad &amp; Tobago","language"=>"Spanish","two_letter_code"=>"es-TT","three_letter_code"=>"es-TTO","locale_id"=>"4096"],
	["name"=>"Tunisia","language"=>"Arabic","two_letter_code"=>"ar-TN","three_letter_code"=>"ar-TUN","locale_id"=>"7169"],
	["name"=>"Tunisia","language"=>"French","two_letter_code"=>"fr-TN","three_letter_code"=>"fr-TUN","locale_id"=>"4096"],
	["name"=>"Turkey","language"=>"English","two_letter_code"=>"en-TR","three_letter_code"=>"en-TUR","locale_id"=>"4096"],
	["name"=>"Turkey","language"=>"Kurdish","two_letter_code"=>"ku-TR","three_letter_code"=>"ku-TUR","locale_id"=>"4096"],
	["name"=>"Turkey","language"=>"Turkish","two_letter_code"=>"tr-TR","three_letter_code"=>"tr-TUR","locale_id"=>"1055"],
	["name"=>"Turkmenistan","language"=>"Turkmen","two_letter_code"=>"tk-TM","three_letter_code"=>"tk-TKM","locale_id"=>"1090"],
	["name"=>"Turks &amp; Caicos Islands","language"=>"English","two_letter_code"=>"en-TC","three_letter_code"=>"en-TCA","locale_id"=>"4096"],
	["name"=>"Turks &amp; Caicos Islands","language"=>"Spanish","two_letter_code"=>"es-TC","three_letter_code"=>"es-TCA","locale_id"=>"4096"],
	["name"=>"Tuvalu","language"=>"English","two_letter_code"=>"en-TV","three_letter_code"=>"en-TUV","locale_id"=>"4096"],
	["name"=>"U.S. Outlying Islands","language"=>"English","two_letter_code"=>"en-UM","three_letter_code"=>"en-UMI","locale_id"=>"4096"],
	["name"=>"U.S. Virgin Islands","language"=>"English","two_letter_code"=>"en-VI","three_letter_code"=>"en-VIR","locale_id"=>"4096"],
	["name"=>"U.S. Virgin Islands","language"=>"Spanish","two_letter_code"=>"es-VI","three_letter_code"=>"es-VIR","locale_id"=>"4096"],
	["name"=>"Uganda","language"=>"Chiga","two_letter_code"=>"cgg-UG","three_letter_code"=>"cgg-UGA","locale_id"=>"4096"],
	["name"=>"Uganda","language"=>"English","two_letter_code"=>"en-UG","three_letter_code"=>"en-UGA","locale_id"=>"4096"],
	["name"=>"Uganda","language"=>"Ganda","two_letter_code"=>"lg-UG","three_letter_code"=>"lg-UGA","locale_id"=>"4096"],
	["name"=>"Uganda","language"=>"Nyankole","two_letter_code"=>"nyn-UG","three_letter_code"=>"nyn-UGA","locale_id"=>"4096"],
	["name"=>"Uganda","language"=>"Soga","two_letter_code"=>"xog-UG","three_letter_code"=>"xog-UGA","locale_id"=>"4096"],
	["name"=>"Uganda","language"=>"Swahili","two_letter_code"=>"sw-UG","three_letter_code"=>"sw-UGA","locale_id"=>"4096"],
	["name"=>"Uganda","language"=>"Teso","two_letter_code"=>"teo-UG","three_letter_code"=>"teo-UGA","locale_id"=>"4096"],
	["name"=>"Ukraine","language"=>"English","two_letter_code"=>"en-UA","three_letter_code"=>"en-UKR","locale_id"=>"4096"],
	["name"=>"Ukraine","language"=>"Russian","two_letter_code"=>"ru-UA","three_letter_code"=>"ru-UKR","locale_id"=>"4096"],
	["name"=>"Ukraine","language"=>"Ukrainian","two_letter_code"=>"uk-UA","three_letter_code"=>"uk-UKR","locale_id"=>"1058"],
	["name"=>"United Arab Emirates","language"=>"Arabic","two_letter_code"=>"ar-AE","three_letter_code"=>"ar-ARE","locale_id"=>"14337"],
	["name"=>"United Arab Emirates","language"=>"English","two_letter_code"=>"en-AE","three_letter_code"=>"en-ARE","locale_id"=>"4096"],
	["name"=>"United Kingdom","language"=>"Cornish","two_letter_code"=>"kw-GB","three_letter_code"=>"kw-GBR","locale_id"=>"4096"],
	["name"=>"United Kingdom","language"=>"English","two_letter_code"=>"en-GB","three_letter_code"=>"en-GBR","locale_id"=>"2057"],
	["name"=>"United Kingdom","language"=>"Scottish Gaelic","two_letter_code"=>"gd-GB","three_letter_code"=>"gd-GBR","locale_id"=>"1169"],
	["name"=>"United Kingdom","language"=>"Welsh","two_letter_code"=>"cy-GB","three_letter_code"=>"cy-GBR","locale_id"=>"1106"],
	["name"=>"United States","language"=>"Cherokee","two_letter_code"=>"chr-US","three_letter_code"=>"chr-USA","locale_id"=>"4096"],
	["name"=>"United States","language"=>"English (United States],","two_letter_code"=>"en-US","three_letter_code"=>"en-USA","locale_id"=>"4096"],
	["name"=>"United States","language"=>"English","two_letter_code"=>"en-US","three_letter_code"=>"en-USA","locale_id"=>"1033"],
	["name"=>"United States","language"=>"Hawaiian","two_letter_code"=>"haw-US","three_letter_code"=>"haw-USA","locale_id"=>"1141"],
	["name"=>"United States","language"=>"Lakota","two_letter_code"=>"lkt-US","three_letter_code"=>"lkt-USA","locale_id"=>"4096"],
	["name"=>"United States","language"=>"Spanish","two_letter_code"=>"es-US","three_letter_code"=>"es-USA","locale_id"=>"21514"],
	["name"=>"Uruguay","language"=>"Spanish","two_letter_code"=>"es-UY","three_letter_code"=>"es-URY","locale_id"=>"14346"],
	["name"=>"Uzbekistan","language"=>"Uzbek","two_letter_code"=>"uz-UZ","three_letter_code"=>"uz-UZB","locale_id"=>"1091"],
	["name"=>"Uzbekistan","language"=>"Uzbek","two_letter_code"=>"uz-UZ","three_letter_code"=>"uz-UZB","locale_id"=>"2115"],
	["name"=>"Vanuatu","language"=>"English","two_letter_code"=>"en-VU","three_letter_code"=>"en-VUT","locale_id"=>"4096"],
	["name"=>"Vanuatu","language"=>"French","two_letter_code"=>"fr-VU","three_letter_code"=>"fr-VUT","locale_id"=>"4096"],
	["name"=>"Vatican City","language"=>"Italian","two_letter_code"=>"it-VA","three_letter_code"=>"it-VAT","locale_id"=>"4096"],
	["name"=>"Venezuela","language"=>"Spanish","two_letter_code"=>"es-VE","three_letter_code"=>"es-VEN","locale_id"=>"8202"],
	["name"=>"Vietnam","language"=>"Vietnamese","two_letter_code"=>"vi-VN","three_letter_code"=>"vi-VNM","locale_id"=>"1066"],
	["name"=>"Wallis &amp; Futuna","language"=>"French","two_letter_code"=>"fr-WF","three_letter_code"=>"fr-WLF","locale_id"=>"4096"],
	["name"=>"Western Sahara","language"=>"Arabic","two_letter_code"=>"ar-EH","three_letter_code"=>"ar-ESH","locale_id"=>"4096"],
	["name"=>"World","language"=>"Arabic","two_letter_code"=>"ar-001","three_letter_code"=>"ar-","locale_id"=>"4096"],
	["name"=>"World","language"=>"English","two_letter_code"=>"en-001","three_letter_code"=>"en-","locale_id"=>"4096"],
	["name"=>"World","language"=>"Esperanto","two_letter_code"=>"eo-001","three_letter_code"=>"eo-","locale_id"=>"4096"],
	["name"=>"World","language"=>"Ido","two_letter_code"=>"io-001","three_letter_code"=>"io-","locale_id"=>"4096"],
	["name"=>"World","language"=>"Interlingua","two_letter_code"=>"ia-001","three_letter_code"=>"ia-","locale_id"=>"4096"],
	["name"=>"World","language"=>"Lojban","two_letter_code"=>"jbo-001","three_letter_code"=>"jbo-","locale_id"=>"4096"],
	["name"=>"World","language"=>"Yiddish","two_letter_code"=>"yi-001","three_letter_code"=>"yi-","locale_id"=>"1085"],
	["name"=>"Yemen","language"=>"Arabic","two_letter_code"=>"ar-YE","three_letter_code"=>"ar-YEM","locale_id"=>"9217"],
	["name"=>"Zambia","language"=>"Bemba","two_letter_code"=>"bem-ZM","three_letter_code"=>"bem-ZMB","locale_id"=>"4096"],
	["name"=>"Zambia","language"=>"English","two_letter_code"=>"en-ZM","three_letter_code"=>"en-ZMB","locale_id"=>"4096"],
	["name"=>"Zimbabwe","language"=>"English","two_letter_code"=>"en-ZW","three_letter_code"=>"en-ZWE","locale_id"=>"12297"],
	["name"=>"Zimbabwe","language"=>"North Ndebele","two_letter_code"=>"nd-ZW","three_letter_code"=>"nd-ZWE","locale_id"=>"4096"],
	["name"=>"Zimbabwe","language"=>"Shona","two_letter_code"=>"sn-ZW","three_letter_code"=>"sn-ZWE","locale_id"=>"4096"],
);
